### ISSUE TITLE
Can the script be modified? 

### ISSUE THREAD

**Issue by peaveyman** [demanuel/NewsUP#1]
This is more of a question. I've just found this app and will be trying it out shortly. My question is can the script be modified to just do the par files and not the rare files?

**Comment by demanuel** [comment]
Yes.

Just check the last commit ;-)

Just set the compression (option RAR_COMPRESSION)  to -1 and it won't compress. It will only par the files.

Regards,
David

**Comment by peaveyman** [comment]
Thanks! 

Another question. Looking at the newsup.conf file, I can't see how to add the groups I want to upload to. Am I missing something?

**Comment by peaveyman** [comment]
Also, if I want to use my own script to do the pars, how can I disable the par2 command? And if I want to upload a directory, or all the files in a directory, what will it use as the subject name?

**Comment by demanuel** [comment]
In that case just use the newsup.pl script directly.

The uploadit.pl script is to make the rar/par creation easier. After the par/rar files are created it simply invokes the newsup.pl.

The subject will allways be the tradicional yenc subject: "filename yenc (part/totalparts)" so it can be parsed for the indexers. However newsup.pl have -comment switch (which you can use 2 times). This switch will make the subject like:

[my first comment] "filename" yenc (1/1) [my second comment]

perl newsup.pl -file filename -comment "my first comment" -comment "my second comment" ....

Please note that the comments will always be surrounded by [ ].

**Comment by peaveyman** [comment]
I'm starting to get the feel for it. Is there any chance the groups could be added to the .conf file? There are 2 groups I upload to all the time, would be useful to be able to add them to the .conf file.

**Comment by peaveyman** [comment]
I must say, you are quick. I just saw the latest commits. :)

**Comment by demanuel** [comment]
I just added the newsgroup option on the conf file :-)

**Comment by peaveyman** [comment]
I'm testing it now. I know it's uploading but I might have to tweak the subject line a little bit. I used to the subject not being in [ ] and having the file count at the end of it. Like this: 

subject [24/24] - "filename" yenc (1/1)

The [24/24] is just the number of files in the post where the first file will have [1/24] and the last will have [24/24]. Is there something I can tweak on my end so you don't have to change it for everybody? The brackets might be fine, I will know in a minute if the indexers pick it up.

**Comment by peaveyman** [comment]
I'm still experimenting with this script. I wanted to try out the par creation but upon running this: perl uploadit.pl -f /home/gary/uploads/George_Strait-Love_Is_Everything-Flac-2013/ -comment George_Strait-Love_Is_Everything-Flac-2013

I get this: Unknown option: comment
You need to configure the switches -file, -name and -group

**Comment by demanuel** [comment]
Added the file counter. You need to invoke newsup.pl with -cfc switch.

It will add a "[fileNumber/TotalFiles]" to the subject.

Please note that uploadit.pl script is a helper script and so, it doesn't support all the options newsup.pl does. Anyway i added the -comment option. 

Please check latest commit.

**Comment by peaveyman** [comment]
I have the latest commit but I must not be understanding quite how to use it. I still get errors when trying to use uploadit.pl. My understanding was that it would create the pars then invoke newsup.pl to do the uploading. I also thought I was supposed to add the options to the command line for uploadit.pl but the errors I get are this: You need to configure the switches -file, -name

**Comment by demanuel** [comment]
ok.

If you're using the uploadit.pl script you need to invoke it like:

minimal options:
perl uploadit.pl -file files_you_want_to_upload -name NZB_name

NZB_name is the filename of the local nzb that will create.

If you want to pass a comment you need to:
perl uploadit.pl -file files_you_want_to_upload -name NZB_name -comment "my comment"

Regards,
David

**Comment by peaveyman** [comment]
I'm using newsup.pl, the file count is there but it has a bracket missplaced.

[Charlie_Robison-Bandera-Flac-1996 [3/26]]

**Comment by demanuel** [comment]
How do you want the subject?

1- [comment [1/20]]
2- comment [1/20]
3- [comment 1/20]

**Comment by peaveyman** [comment]
My personal preference is like this: 

Reba_McEntire-I'll_Be-Flac-2000 [02/29] - "cover.jpg" yEnc (1/1)

So number 2 I believe.

**Comment by demanuel** [comment]
Please check the latest commit. ;-)

**Comment by peaveyman** [comment]
That's just right, for me at least. Thanks!!!

**Comment by demanuel** [comment]
Thanks for using newsup :-)

**Comment by demanuel** [comment]
Hi!

Just to tell you that isn't required that the comment should be one word... You can pass it on the command line with "". Example:

perl newsup.pl -comment "Subject comment with spaces between" ....

If you don't add the " then you need to replace the spaces with _. Example: Subject_comment_with_spaces_between

Hope it helps your work :-)

Regards,
David Santiago

**Comment by peaveyman** [comment]
I understand what you are saying but the comment is the subject of the post and the way I have it setup is the way the indexes like it. I copy a folder into my upload folder. I have a script that I run on it that creates the pars and renames the folder in the manner I need. I then use that folder name as the subject. With other up loaders they use the folder name as the subject and with newsup I use it as the comment which amounts to the same thing.

**Comment by demanuel** [comment]
Got it.

Feel free to open tickets, if you have any suggestion, if you think something can be improved or you found some bug,

**Comment by peaveyman** [comment]
One suggestion I would have.
Include the par and rare creation right into newsup.pl. Have it create the pars and use the comment or subject if you will as the name of the par files also. This way every thing is done with one command.

**Comment by demanuel** [comment]
I'm sorry but i'm not going to do that. I don't want to make the newsup.pl bloated, which will then make it harder to maintain and slower

There's the uploadit script that does exactly that you described:
`
perl uploadit.pl -f /folder/with/files -name my_files_xpto -comment folder_with_files
`
This will create articles with the subject:
*folder_with_files "my_files.part01.rar" yenc (1/1)*
*folder_with_files "my_files.par2" yenc (1/1)*

and the nzb file *my_files.nzb* will be created.

**Comment by peaveyman** [comment]
That's fine. Just a thought. I ran uploadit.pl as you suggested and got this: sh: -c: line 0: syntax error near unexpected token `)'

**Comment by demanuel** [comment]
Can you provide the full output and the newsup.conf ?

**Comment by peaveyman** [comment]
Here is the command I used and full output:

perl uploadit.pl -f /home/gary/uploads/Allison_Moorer-Crows-Flac-2010/ -name Allison_Moorer-Crows-Flac-2010 -comment Allison_Moorer-Crows-Flac-2010
Splitting files!
Checksum'ing the files
Creating parity files
sh: -c: line 0: syntax error near unexpected token `)'
sh: -c: line 0: `/usr/bin/par2 c -r20 /tmp/Allison_Moorer-Crows-Flac-2010 /tmp/Crows - 12 - It's Gonna Feel Good (When It Stops Hurting).flac /tmp/Crows - 10 - Like the Rain.flac /tmp/cover.jpg /tmp/Crows - 02 - Goodbye to the Ground.flac /tmp/Crows - 04 - The Broken Girl.flac /tmp/Crows - 05 - Should I Be Concerned.flac /tmp/Allison Moorer - Crows.log /tmp/Allison Moorer - Crows.jpg /tmp/Crows - 03 - Just Another Fool.flac /tmp/Allison Moorer - Crows.cue /tmp/Crows - 08 - The Stars & I (Mama's Song).flac /tmp/Crows - 06 - When You Wake Up Feeling Bad.flac /tmp/Crows - 07 - Easy in the Summertime.flac /tmp/Crows - 11 - Sorrow (Don't Come Around).flac /tmp/Crows - 01 - Abalone Sky.flac /tmp/Crows - 13 - Crows.flac /tmp/Crows - 09 - Still This Side of Gone.flac /tmp/00.m3u /tmp/Allison_Moorer-Crows-Flac-2010.sfv'

Starting upload
No files to upload!

Here is my newsup.conf:

[server]
server= 
port= 563
connections= 30

[auth]
user= 
password= 

[metadata]
client= NewsUP

[upload]
uploader=
newsgroup= alt.binaries.sounds.lossless.country, alt.binaries.sounds.flac

[generic]
headerCheck= 1
monitoringPort = 8675


[script_vars]
############################
#
# Variables
############################
# Path to newsup script
PATH_TO_UPLOADER=/usr/bin/newsup.pl
# Path to RAR
PATH_TO_RAR=/usr/bin/rar
# RAR volume size in megabytes 
RAR_VOLUME_SIZE=50
# RAR compression level
# If RAR_COMPRESSION is -1 then it will skip it
RAR_COMPRESSION=-1
# RAR Password
RAR_PASSWORD=newsup
# Path to PAR2
PATH_TO_PAR2=/usr/bin/par2
# Folder to where the scripts files should be written
# It's obigatory to terminate on the separator folder char.
TEMP_DIR=/tmp/
# Par recovery %
PAR_REDUNDANCY=20
# Randomize Names
# The names are toggled
RANDOMIZE_NAMES=0

**Comment by demanuel** [comment]
Got the error. Basically the files weren't being escaped. They are now.

Please check latest commit

**Comment by peaveyman** [comment]
Can the cfc switch be included in the uploadit.pl command?

**Comment by demanuel** [comment]
Yes.

Just edit the newsup.conf file and add the -cfc to the option PATH_TO_UPLOADER.

It should work.

**Comment by peaveyman** [comment]
Tried that, I get this: You need to define a valid path to newsup. Please change the variable PATH_TO_UPLOADER on the newsup.conf file

**Comment by peaveyman** [comment]
I ran this command: perl uploadit.pl -f /home/gary/uploads/Allison_Moorer-Crows-Flac-2010/ -name Allison_Moorer-Crows-Flac-2010 -comment Allison_orer-Crows-Flac-2010

The out come I want is Allison_Moorer-Crows-Flac-2010 [filecount] - "filename" yenc (parts)

What I got was this: Crows - 12 - It's Gonna Feel Good (When It Stops Hurting).flac" yenc (/39)

**Comment by demanuel** [comment]
It looks like something isn't being escaped very well.

Can you check the latest commit? I added -debug flag. 
Can you please the uploadit script with -debug and paste here the output?

**Comment by peaveyman** [comment]
I will do that but it will be later since I'm at work.

**Comment by peaveyman** [comment]
Where do I need to place -debug in the command?

**Comment by demanuel** [comment]
hi.

You just need to invoke with it. Like this:

perl uploadit.pl -f /home/gary/uploads/Allison_Moorer-Crows-Flac-2010/ -name Allison_Moorer-Crows-Flac-2010 -comment Allison_orer-Crows-Flac-2010 **-debug**

**Comment by peaveyman** [comment]
I get this: Unknown option: debug

**Comment by demanuel** [comment]
Can you paste here the full cmd line?

**Comment by peaveyman** [comment]
I downloaded the latest version and then tried to use the -debug. Here is the cmd I used:

perl uploadit.pl -f /home/gary/uploads/Allison_Moorer-Crows-Flac-2010/ -name Allison_Moorer-Crows-Flac-2010 -comment Allison_orer-Crows-Flac-2010 -debug

**Comment by demanuel** [comment]
I commited locally, but forgot to push to github. Please update your version :-)

**Comment by peaveyman** [comment]
Here is the debug output. I don't see anything out of the ordinary.


perl uploadit.pl -f /home/gary/uploads/Allison_Moorer-Crows-Flac-2010/ -name Allison_Moorer-Crows-Flac-2010 -comment Allison_orer-Crows-Flac-2010 -debug
Splitting files!
Checksum'ing the files
        CRC32 Crows - 12 - It's Gonna Feel Good (When It Stops Hurting).flac dcb236ce
        CRC32 Crows - 10 - Like the Rain.flac e2cb2f6a
        CRC32 cover.jpg 4e3986fe
        CRC32 Crows - 02 - Goodbye to the Ground.flac a4ea6de3
        CRC32 Crows - 04 - The Broken Girl.flac 460e30f3
        CRC32 Crows - 05 - Should I Be Concerned.flac b349cdad
        CRC32 Allison Moorer - Crows.log 91fb2dd2
        CRC32 Allison Moorer - Crows.jpg 690e6535
        CRC32 Crows - 03 - Just Another Fool.flac 06f42fc4
        CRC32 Allison Moorer - Crows.cue 0d8452f9
        CRC32 Crows - 08 - The Stars & I (Mama's Song).flac 713b9942
        CRC32 Crows - 06 - When You Wake Up Feeling Bad.flac a325a1d0
        CRC32 Crows - 07 - Easy in the Summertime.flac 3d950af8
        CRC32 Crows - 11 - Sorrow (Don't Come Around).flac 9642e5e1
        CRC32 Crows - 01 - Abalone Sky.flac 12a099be
        CRC32 Crows - 13 - Crows.flac a2104603
        CRC32 Crows - 09 - Still This Side of Gone.flac 32d6c166
        CRC32 00.m3u 817fe5eb
Creating parity files
/usr/bin/par2 c -r20 /tmp/Allison_Moorer-Crows-Flac-2010 "/tmp/Crows - 12 - It's Gonna Feel Good (When It Stops Hurting).flac" "/tmp/Crows - 10 - Like the Rain.flac" "/tmp/cover.jpg" "/tmp/Crows - 02 - Goodbye to the Ground.flac" "/tmp/Crows - 04 - The Broken Girl.flac" "/tmp/Crows - 05 - Should I Be Concerned.flac" "/tmp/Allison Moorer - Crows.log" "/tmp/Allison Moorer - Crows.jpg" "/tmp/Crows - 03 - Just Another Fool.flac" "/tmp/Allison Moorer - Crows.cue" "/tmp/Crows - 08 - The Stars & I (Mama's Song).flac" "/tmp/Crows - 06 - When You Wake Up Feeling Bad.flac" "/tmp/Crows - 07 - Easy in the Summertime.flac" "/tmp/Crows - 11 - Sorrow (Don't Come Around).flac" "/tmp/Crows - 01 - Abalone Sky.flac" "/tmp/Crows - 13 - Crows.flac" "/tmp/Crows - 09 - Still This Side of Gone.flac" "/tmp/00.m3u" "/tmp/Allison_Moorer-Crows-Flac-2010.sfv"
Starting upload
/home/gary/NewsUP/newsup.pl -f "/tmp/Crows - 12 - It's Gonna Feel Good (When It Stops Hurting).flac" -f "/tmp/Crows - 10 - Like the Rain.flac" -f "/tmp/cover.jpg" -f "/tmp/Crows - 02 - Goodbye to the Ground.flac" -f "/tmp/Crows - 04 - The Broken Girl.flac" -f "/tmp/Crows - 05 - Should I Be Concerned.flac" -f "/tmp/Allison Moorer - Crows.log" -f "/tmp/Allison Moorer - Crows.jpg" -f "/tmp/Crows - 03 - Just Another Fool.flac" -f "/tmp/Allison Moorer - Crows.cue" -f "/tmp/Crows - 08 - The Stars & I (Mama's Song).flac" -f "/tmp/Crows - 06 - When You Wake Up Feeling Bad.flac" -f "/tmp/Crows - 07 - Easy in the Summertime.flac" -f "/tmp/Crows - 11 - Sorrow (Don't Come Around).flac" -f "/tmp/Crows - 01 - Abalone Sky.flac" -f "/tmp/Crows - 13 - Crows.flac" -f "/tmp/Crows - 09 - Still This Side of Gone.flac" -f "/tmp/00.m3u" -f "/tmp/Allison_Moorer-Crows-Flac-2010.sfv" -f "/tmp/Allison_Moorer-Crows-Flac-2010.par2" -f "/tmp/Allison_Moorer-Crows-Flac-2010.vol000+001.par2" -f "/tmp/Allison_Moorer-Crows-Flac-2010.vol001+002.par2" -f "/tmp/Allison_Moorer-Crows-Flac-2010.vol003+004.par2" -f "/tmp/Allison_Moorer-Crows-Flac-2010.vol007+008.par2" -f "/tmp/Allison_Moorer-Crows-Flac-2010.vol015+016.par2" -f "/tmp/Allison_Moorer-Crows-Flac-2010.vol031+032.par2" -f "/tmp/Allison_Moorer-Crows-Flac-2010.vol063+064.par2" -f "/tmp/Allison_Moorer-Crows-Flac-2010.vol127+128.par2" -f "/tmp/Allison_Moorer-Crows-Flac-2010.vol255+145.par2" -nzb Allison_Moorer-Crows-Flac-2010
Starting connection 1 for uploading
Starting connection 2 for uploading
Starting connection 3 for uploading
Starting connection 4 for uploading
Starting connection 5 for uploading
Starting connection 6 for uploading
Starting connection 7 for uploading
Starting connection 8 for uploading
Starting connection 9 for uploading
Starting connection 10 for uploading
Starting connection 11 for uploading
Starting connection 12 for uploading
Starting connection 13 for uploading
Starting connection 14 for uploading
Starting connection 15 for uploading
Starting connection 16 for uploading
Starting connection 17 for uploading
Starting connection 18 for uploading
Starting connection 19 for uploading
Starting connection 20 for uploading
Starting connection 21 for uploading
Starting connection 22 for uploading
Starting connection 23 for uploading
Starting connection 24 for uploading
Starting connection 25 for uploading
Starting connection 26 for uploading
Starting connection 27 for uploading
Starting connection 28 for uploading
Starting connection 29 for uploading
Starting connection 30 for uploading

**Comment by demanuel** [comment]
Got the problem! It should be fixed now. Please update to the latest version.

**Comment by peaveyman** [comment]
Testing now.

**Comment by peaveyman** [comment]
This cmd: perl uploadit.pl -f /home/gary/uploads/Allison_Moorer-Crows-Flac-2010/ -name Allison_Moorer-Crows-Flac-2010 -comment Allison_Moorer-Crows-Flac-2010 -debug

Gave me this file name: Allison_orMoorer-Crows-Flac-2010 "Crows - 12 - It's Gonna Feel Good (When It Stops Hurting).flac" yenc (1/39)

**Comment by peaveyman** [comment]
Sorry for being so much trouble. :)

**Comment by demanuel** [comment]
No problem ;-)

What's the problem with the subject? I'm not getting...

**Comment by peaveyman** [comment]
Allison_orMoorer-Crows-Flac-2010

This should be Allison_Moorer-Crows-Flac-2010

**Comment by demanuel** [comment]
That's very strange. I'm not changing the data the user pass to the program....
Can you provide again the -debug output?

**Comment by peaveyman** [comment]
Well, I typed out the command again and it is working now. The file name is correct. Now if I could just get the file count in the header looks like all would be good.

**Comment by demanuel** [comment]
Can you try -cfc on the config file? I changed the script to accept it. The error reported in the past shouldn't happen anymore.

**Comment by peaveyman** [comment]
Like this: PATH_TO_UPLOADER=/home/gary/NewsUP/newsup.pl -cfc  

I will try it out in a bit.

**Comment by demanuel** [comment]
yes. Ok

**Comment by peaveyman** [comment]
File count is there.

**Comment by demanuel** [comment]
Cool. I'm going to close this, is that ok?

**Comment by peaveyman** [comment]
Yes that's ok

**Comment by demanuel** [comment]
Sorry didn't saw your previous question.

The uploadit.pl is a script to help you with par and rar creation. This means that the options defined on the newsup.conf file will be used on the newsup.pl. So if the headerCheck option is set as 1, the newsup.pl will do the headercheck
