### ISSUE TITLE
Upload Subject

### ISSUE THREAD

**Issue by demanuel** [demanuel/NewsUP#10]
Well....

It seems there's no standard way of setting the subject. So i'm going to set this completely arbitrary.

The subject from now on will be

**$COMMENT1 [$CURRENT/$TOTAL] - "$FILENAME" ($SEGMENT/$SEGMENT_TOTAL) [$COMMENT2]**

### Description

* $COMMENT1 - first comment. It can multiple words (a sentence). No delimiting character.

* $CURRENT - current number of file being upload. If you are uploading only one file then it will be always 1. If you are uploading 10 files, and from these 10 files it's currently uploading, for example, the sixth, then it will be 6

* $TOTAL - the total number of files to be upload. If you choose a folder to be upload this will be the number of files of the folder (that will be uploaded).

* $FILENAME - filename. It will be delimited by 2 **"**

* $SEGMENT - number of the segment that the is being uploaded.

* $SEGMENT_TOTAL - total number of segments

* $COMMENT2 - Second comment. Same rules as $COMMENT1 (but delimited by [] ).

# Example:
If we have
```
FOLDER/
 * File 1
 * File 2
 * Files 3
```

## Example 1
```perl -f Folder/ ```
It will produce the following subjects:
```
[1/3] - "File 1" (AA/BB)
[2/3] - "File 2" (CC/DD)
[3/3] - "File 3" (EE/FF)
```
## Example 2
```perl -f Folder/File 1```
It will produce the following subject:
```[1/1] - "File 1" (AA/BB)```

## Example 3
```perl -f Folder/File 2```
It will produce the following subject:
```[1/1] - "File 2" (AA/BB)```

## Example 4
```perl -f Folder/File 1 -comment "This is the first comment"```
It will produce the following subject:
```This is the first comment [1/1] - "File 1" (AA/BB)```

## Example 5
```perl -f Folder/File 1 -comment "This is the first comment" -comment "The end comment"```
It will produce the following subject:
```This is the first comment [1/1] - "File 1" (AA/BB) [The end comment]```

## Example 6
```perl -f Folder/ -comment "This is the first comment" -comment "The end comment"```
It will produce the following subject:
```
This is the first comment [1/3] - "File 1" (AA/BB) [The end comment]
This is the first comment [1/3] - "File 2" (CC/DD) [The end comment]
This is the first comment [1/3] - "File 3" (EE/FF) [The end comment]
```

## Note:
AA, BB, CC, DD,EE,FF - are the counters of the segments. This is dependent of the size and of the read and the size of the file.

# Modifications required
This will make the switch -cfc obsolete, and it will be removed

**Comment by peaveyman** [comment]
It looks like Example 4 gives me almost what I need. If you have access to usenet headers look on alt.binaries.lossless.country and look for my user name. You can see the format I need. Notice the dash I added to the example below.

Example 4

perl -f Folder/File 1 -comment "This is the first comment"
It will produce the following subject:
This is the first comment [1/1] - "File 1" (AA/BB)

**Comment by demanuel** [comment]
@peaveyman, thanks! Nice catch!

Updated the issue.

I'm going to leave this issue open for a while, so i can get more opinions

**Comment by peaveyman** [comment]
Sounds good. My personal preference would be to pick up the folder name to use for the 1st comment but I don't know if that's possible.

**Comment by demanuel** [comment]
@peaveyman, please check the branch "10"

https://github.com/demanuel/NewsUP/archive/10.zip

It should also reflect the changes on the subject.

**Comment by shillshocked** [comment]
I like the idea. It's good to have as much control over the uploader as possible.

**Comment by demanuel** [comment]
@shillshocked thx for opinion.

**Comment by demanuel** [comment]
I just merged the branch 10 with master, so what's described in the issue, is already reflected.

Please warn me of bug you may find
