### ISSUE TITLE
Now it just doesn't upload anything

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#11]
Is there a debug option?

**Comment by peaveyman** [comment]
Put -debug at the end of the command

**Comment by shillshocked** [comment]
"Unknown option: debug"

**Comment by peaveyman** [comment]
Paste the command in here

**Comment by shillshocked** [comment]
newsup.pl -debug

**Comment by peaveyman** [comment]
Isthatall? I think you need a few more arguments

**Comment by shillshocked** [comment]
I did previously...but now I am just doing a test since it doesn't work.

**Comment by shillshocked** [comment]
At any rate, tried another server and it seems to work. Have no idea how to get the debug option to work.

I did get a cryptic message at the end of posting though:

\C is deprecated in regex; marked by <-- HERE in m/(\C <-- HERE )/ at /usr/share/perl5/site_perl/URI/Escape.pm line 205.

**Comment by peaveyman** [comment]
The developer will have to handle this one

**Comment by demanuel** [comment]
@shillshocked 
It's not working for a specific server, or it doesn't work at all ?

The -debug only exists at this moment for the uploadit.pl script.

Are you using branch master, or any other branch? Are you using SSL?

**Comment by demanuel** [comment]
I merged the #10, with the master. So you can try the master branch? - The SSL version is downgraded, and you will have the subject working as described as in #10

**Comment by shillshocked** [comment]
I don't use uploadit.pl, so I can't debug it.

**Comment by demanuel** [comment]
:-)

I already rollback the changes i had done. Can you try it now? if you still want to debug it, then on the version with the problem, please edit the Uploader.pm and on the line 12 uncomment the debug3.
The line should be:
use IO::Socket::SSL qw(debug3);

**Comment by shillshocked** [comment]
I think it was just a buggy upload server issue.

**Comment by demanuel** [comment]
If the issue still happens, let me know :-)
