### ISSUE TITLE
Can't use subject with a ":" in the subject line

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#12]
It just cuts off the subject at that point.

**Comment by demanuel** [comment]
Strange... I don't find any problem:

http://imgur.com/v8azFBS


Can you paste your command line? Specifically the part with ":" ?

**Comment by demanuel** [comment]
@shillshocked Can you provide a example and paste your comand line and your configuration file?

Thanks

**Comment by shillshocked** [comment]
I did it with the newsupseq.sh script. But even without the script it's still an issue.

**Comment by demanuel** [comment]
@shillshocked can you provide a command line example? I'm was able to put ":" as the image i posted above shows.

I want to know how are you running it :-)

**Comment by demanuel** [comment]
@shillshocked, i'm closing this as there was no more info. Feel free to reopen it with the info i asked.

Thx

**Comment by shillshocked** [comment]
I do:

http://i.imgur.com/b4c9NkR.jpg
http://i.imgur.com/Q3oORFn.jpg

Used with the newsupseq.sh in the scripts.

I cannot use colons. It just cuts off at the place of the colon.

**Comment by demanuel** [comment]
Can you use newsup and check if this happens ?

Although ":" it's dangerous to use, i'm not able to replicate your issue:

Steps i did:
```
perl newsup.pl -f test\:\ stuff.html
```

Then i connected to the usenet server and i got:

```
From: NewsUP <NewsUp@somewhere.cbr>
Newsgroups: alt.binaries.test
Subject: "test: stuff.html" yenc (38/40)
```

As you can see the subject contains the ':' and it's enclosed between "


At least it seems not to be a newsup bug

**Comment by shillshocked** [comment]
Ah, so you enclose it in backlashes? I was just preceding it with one.

**Comment by demanuel** [comment]
:-)

Yes otherwise, if i'm not mistaken, bash interprets it as a function :-)


Closing this issue, as it's not reproducible, and it's an user error

**Comment by shillshocked** [comment]
Just tried your way and I still get the problem...

**Comment by shillshocked** [comment]
Also, I cannot use "/" in the subject either. Same problem.

**Comment by demanuel** [comment]
I can't even have names with '/'.... Are you trying that on windows?
The ':' works as i already proved before.  


     On Sunday, August 9, 2015 5:06 AM, shillshocked <notifications@github.com> wrote:
   

 Also, I cannot use "/" in the subject either. Same problem.—

**Comment by shillshocked** [comment]
Could be my usenet provider...

I'm posting under Linux.
