### ISSUE TITLE
.part1.rar

### ISSUE THREAD

**Issue by maximuml** [demanuel/NewsUP#13]
It seems first part is not included at the bash
for example:
for dir in *; do perl uploadit.pl -directory "$dir" -debug; done;

output:
Pre Processing the input
Invoking: "/usr/local/bin/rar" a -m0 -v209715 -ep -ed -r -rr10% "/home/user7/hdd2/tmp/archive1.rar" "archive1"
$VAR1 = [
          '/home/user7/hdd2/tmp/archive1.part2.rar'
        ];

Creating SFV file
archive1.part2.rar 7e1693c2
$VAR1 = [
          '/home/user7/hdd2/tmp/archive1.part2.rar',
          '/home/user7/hdd2/tmp/archive1.sfv'
        ];

Creating Partity archives
Invoking: /usr/local/bin/par2 c -r20 "/home/user7/hdd2/tmp/archive1.par2" "/home/user7/hdd2/tmp/archive1.part2.rar" "/home/user7/hdd2/tmp/archive1.sfv"
$VAR1 = [
          '/home/user7/hdd2/tmp/archive1.part2.rar',
          '/home/user7/hdd2/tmp/archive1.sfv',
          '/home/user7/hdd2/tmp//archive1.par2',
          '/home/user7/hdd2/tmp//archive1.vol003+004.par2',
          '/home/user7/hdd2/tmp//archive1.vol255+145.par2',
          '/home/user7/hdd2/tmp//archive1.vol031+032.par2',
          '/home/user7/hdd2/tmp//archive1.vol015+016.par2',
          '/home/user7/hdd2/tmp//archive1.vol000+001.par2',
          '/home/user7/hdd2/tmp//archive1.vol007+008.par2',
          '/home/user7/hdd2/tmp//archive1.vol127+128.par2',
          '/home/user7/hdd2/tmp//archive1.vol063+064.par2',
          '/home/user7/hdd2/tmp//archive1.vol001+002.par2'
        ];

part1.rar not included!!!!!!!!!!!!!!!
Am i doing something wrong????

**Comment by demanuel** [comment]
I parse the output of the rar command and if you use the output format <file>.partxx.rar, for some reason the rar doesn't yield the part01.rar file.

You need to use the old nomeclature of .r00,r01.... Please add on your rar arguments  "-vn"

**Comment by maximuml** [comment]
ok, lets rar Blu-ray ~30Gb, rar will make 150 parts.
Parts from 0 to 99 will be named .r00 and so on but other parts will have a name starting with s - .s00, .s01, .s02 and so on. 
This parts (.s00) also not included in .sfv and .par2 and not loaded into uploadit.pl (((((((((

**Comment by demanuel** [comment]
I never had the need to have more than 100 parts, so i never though about that :-)
It's a bug.(well for now you'll need to use another tool to split the files. You can still use newsup.pl to upload them, though...)

That issue .SXX doesn't happen when you use the partXX way?

**Comment by maximuml** [comment]
Only issue with part1.rar not included!

**Comment by demanuel** [comment]
@maximuml can you test the latest version?

**Comment by maximuml** [comment]
Seems like working fine with files < 20Gb
Need time to check big files

**Comment by demanuel** [comment]
Please update here your results and advise if this can be closed.

**Comment by maximuml** [comment]
Working GOOD now!!!!
