### ISSUE TITLE
Any way to repost missing segments after the fact?

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#16]
Just wonder if it's possible. I know you can do it with some clients.

**Comment by demanuel** [comment]
If you have the headercheck option and a segment is missing, the segment will be reposted (or at least it will re-try to repost it). If after reposting the segment is still missing, then there's no way.

Can you provide an example how it should work? Which clients do that?

**Comment by shillshocked** [comment]
Sometimes the segments don't repost. Is there a way to rig it to do it again?

**Comment by shillshocked** [comment]
As an example, Jbinup can do headercheck on file infinitely until they repost. Camel PowerPost can repost individual segments that you can select. There is also even ways to do it manually, but that's a bit too technical for me.

Maybe there is a way we could put in the config how many times to try reposting. Ie. 1, 2, 10 or infinite (use the value 0)

**Comment by demanuel** [comment]
Well initially it was doing infinitelly, but then the people complained that it would be get stuck and not finishing posting.

:-P

I can do that. I'll put a option on the config file.

**Comment by shillshocked** [comment]
Awesome, looking forward to that!

**Comment by demanuel** [comment]
On the latest version is doing 3 times. I need to put a variable :-)

**Comment by shillshocked** [comment]
A variable would be nice. :)

**Comment by demanuel** [comment]
Done. Check the option -retry or headerCheckRetries :-)

Check the readme for more info.

Please note that there's no "infinite" retries. Although you can put the biggest number you want...

**Comment by shillshocked** [comment]
Good!
