### ISSUE TITLE
Getting an error with the new version

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#17]
Can't use an undefined value as a symbol reference at /bin/NewsUP-master/lib/Net/NNTP/Uploader.pm line 199.

**Comment by demanuel** [comment]
fixed.

The new version is a total rewrite. Can you please test it? It should be faster, since i'm now using C to do yenc

**Comment by shillshocked** [comment]
Will do...just waiting on my usenet provider to fix a bug.
