### ISSUE TITLE
Custom Headers

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#18]
This is something I would love to see. Already possible in Xnews and some other clients, but it's not as common a feature in binary posters.

Then you could add things like "Reply-To", "Organization", or other valuable header info that you might want downloaders to see.

I know this can be done easily using IHAVE instead of POST, which goes like:

ihave <18f87sf87s87@example.com>
From: email@example.com
Subject: test message
Newsgroups: alt.binaries.test
Path: not-for-mail
Date: 7 September 2015
Message-ID: <18f87sf87s87@example.com>
Body: 

Test message.

.

You can test that by telneting into your usenet provider yourself. The code should work, although of course message id has to be unique and is the same in the first line and the Message-Id line.

Using this method will allow you to put ANY custom header into the usenet message header.

Only problem is that only some servers support IHAVE. Maybe you could make an option for IHAVE?

**Comment by demanuel** [comment]
Why ihave and not a normal post?

**Comment by shillshocked** [comment]
ihave gives you more flexibility in terms of posting options. You can control the headers better.

**Comment by demanuel** [comment]
@shillshocked can you give some example how the user would setup this?

WOuld it be on conf file, command line?

**Comment by shillshocked** [comment]
I think both conf and command-line options would be best, but it would of course be easiest to do it through a conf file.

**Comment by demanuel** [comment]
So no dynamic options.

Basically static options, like for example in the config file?

[EXTRA_HEADERS]
header1= my header one
header2= my header two

**Comment by shillshocked** [comment]
Exactly. :D

**Comment by demanuel** [comment]
Please check the latest commit.

**Comment by demanuel** [comment]
Closing the issue as there's no reply
