### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by Aparratus** [demanuel/NewsUP#25]
Posting a folder of about 4GB results in the NewsUP process getting killed by the OS because it consumes too much memory. This happens after about 60-70% is complete.

The system I am attempting this on has 2GB of memory in total, and I can see the memory usage slowly climb as NewsUP is posting the files. Eventually, all available memory is consumed, including SWAP, and the process is automatically killed mid-posting.

Please advise whether there is something I am not doing properly, or whether this is an issue in the code. If you require any further help in diagnosing this, I am at your disposal.

[newsup_config.txt](https://github.com/demanuel/NewsUP/files/73040/newsup_config.txt)

The posting is executed with:
```
perl newsup.pl -file <folder>
```

**Comment by demanuel** [comment]
Thanks for the report. 

I just re-run newsup with valgrind and it's reporting a memory leak. I'll take a look into it.

BTW, what OS are you using?

**Comment by Aparratus** [comment]
Debian 8 in an OpenVZ container.

**Comment by demanuel** [comment]
Can you test the latest version?

I'll close this issue after your confirmation that it's solved.

**Comment by Aparratus** [comment]
Issue resolved. Barely any memory used now - thank you and well done.

**Comment by demanuel** [comment]
Super!

Feel free to raise any issue you might find it needs improvement!

Thanks!
