### ISSUE TITLE
SFV not generating properly? (Uploadit.pl)

### ISSUE THREAD

**Issue by incorpusyehtee** [demanuel/NewsUP#28]
From the .SFV generated by Uploadit.pl (Windows zip)
```
_redacted_.rar 81928fa2
_redacted_.r00 399efb71
_redacted_.r01 2c0ea05a
_redacted_.r02 5c5f4bad
_redacted_.r03 e2b7b948
_redacted_.r04 aadbddea
_redacted_.r05 6cb78004
_redacted_.r06 ddcae293
_redacted_.r07 1f50ee4d
_redacted_.r08 4fa02ffc
_redacted_.r09 cdeb46b8
_redacted_.r10 d41a2d29
_redacted_.r11 dbf6c718
_redacted_.r12 74e318a5
```

Actual CRC results mismatch, confirmed the real CRC with a few tools:
![sfvproper](https://cloud.githubusercontent.com/assets/8435612/12704246/731c8936-c824-11e5-8c61-8d32a786ae7d.png)

![sfvmismatch](https://cloud.githubusercontent.com/assets/8435612/12704244/6fc7e7da-c824-11e5-8dce-6284e0299a69.png)

**Comment by demanuel** [comment]
Let me check.

You're running the uploadit on windows platform right?

Since the SFV, is done with an official perl library, i'm assuming that the issue is how i'm reading the file.

**Comment by incorpusyehtee** [comment]
Works now, thanks much!
