### ISSUE TITLE
Can you give an example of how to post using this?

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#3]
I filled in the config and tried to follow the example. No matter what I do, I keep getting the generic error: Please check the parameters ('server', 'port', 'username'/'password', 'connections','uploader' and 'newsgoup')

I've triple-checked all the parameters but it still doesn't work.

Can you post a working example and a working config with all the parameters filled in? I am trying to post folders of files.

**Comment by demanuel** [comment]
Hi!

I just found out i had a bug while parsing the configuration file for the PORT option. It's fixed now.
Please update your newsup.pl script. Please note that all the config options can be run with command
line switches. If you want to check if this is the issue affecting you, without updating your script run:
perl newsup.pl ...your parameters... -port <put your port here>
If it was, then that was the culprit :-)
If it still doesn't work, please update this ticket, with your command line.

There are two ways you can upload using NewsUp:
1- With the uploadit.pl script (This will rar, par and upload - The upload is done by invoking the newsup.pl script).
2- With the newsup.pl script.

#Your Questions:
##Working Config file
```
[server]
server= upload.server.com
port= 563
connections= 2

[auth]
user= username
password= password

[metadata]
client= NewsUP

[upload]
uploader= NewsUP <NewsUp@somewhere.cbr>
newsgroup= alt.binaries.test

[generic]
headerCheck= 1
monitoringPort = 8675
```

Now with this config file on your ```home_folder/.config``` folder you can run newsup.pl as:
perl newsup.pl -f folder_with_files_inside_to_upload/ -cfc -comment "my comment"

Is this info enough for you? Please provide feedback.

**Comment by shillshocked** [comment]
It's uploading now. Only thing is, header checking ain't working so well because my server lags. I generally use one server to upload and another faster server for the header checks. Would this be possible to implement?

**Comment by demanuel** [comment]
Cool that it's working now! :-D

Can i ask you what OS are you using? And what speeds are you getting?

I can implement it, but i'm not understanding how it will work... :-(
If you're uploading to server A, and this server takes time to process the upload, how will the articles be available on the other server?

They aren't uploaded in order because, you are uploading multiple files at the same time (usually one per connection). If i change the order, then it will take a hit in the speed. 
Is the order on the server that important? If you don't use the "-cfc" switch it will stop putting the counter in the subject.

**Comment by shillshocked** [comment]
Speeds are great, sometimes maxing out my fiber connection with just 10 threads. I use up to 250 threads in another program.

I would rather have it upload one file at a time, sequentially, so that the order is preserved. I post a lot of content and it's crucial it stays ordered so that users can ensure they get the entire download set (sometimes parts go missing against my best efforts, depending on server completion/retention).

That being said, the cfc option turned off is probably my best bet. I can program a script to add my own counter then for the batch.

It would be nice to be able to specify only one file at a time with the program regardless. It may be a bit slower, but you can upload chunks of the file via threads, correct?

**Comment by demanuel** [comment]
If you choose to upload only one file, and you specify for example 10 threads, the file will be splitted in 10 parts (1 process will be responsible for 1/10th of the file) and all of them will be uploaded at the same time :-)

**Comment by shillshocked** [comment]
Here is a rudimentary newsupfilebyfile.sh bash script for those who are interested:

```
MYBASENAME=$(basename "$PWD")
totalfiles=$(ls -1 | wc -l)
counter=1
for file in "$PWD"/*
do
  perl ~/bin/NewsUP-master/newsup.pl -f "$file" -comment "FILL COMMENT IN HERE - $MYBASENAME [$((counter++))/$totalfiles]"
done
```

**Comment by demanuel** [comment]
The headercheck option works like this:
After a process finishes the upload of *all* the segments, it will do the headercheck. For every failed headercheck it will sleep 20 seconds. I can make this 20 seconds user defined.

Can i use your script? I'll put it on the folder scripts. I'll also put your name and any other info you want.

I can also add the secondary server for header check.

If you agree I'm going to close this ticket, as the original issue is solved. Please open new issues for the new features.

**Comment by shillshocked** [comment]
I consider it a bandaid solution. Not the best, but workable.

There's another approach you could take towards header-checking that may be more efficient.

Take a look at Jbinup, and how they do it. You do an entire batch of posting. And then you run the header check. The advantage of doing this is speed, as well as the fact that you can choose to do it or not afterward. I find it works efficiently, although I'm not sure if it posts out of order sometimes. Perhaps.

If you want to use the code, go ahead. You don't need to credit me for anything.

I would still prefer it to work within the program if possible, but my perl-foo is a bit rusty and I haven't wrapped my head around how to do an optional routine to post sequentially (possibly with header checks at the end).

**Comment by demanuel** [comment]
I opened the issue 5 and issue 6, for those headercheck related features.

I don't think i'll implement the order issue... It would need a rewrite, with no obvious gain (for me) . Plus you can use workarounds, like the one you pasted - for the NZBs issue you can do something like:
```
(echo "<nzb>" && grep -s -h -a -i -v -e nzb -e xml *nzb && echo "</nzb>") > new.nzb
```
You can open an enhancement issue if you want (i won't close it), but it will implemented only when i'll rewrite the newsup from scratch (which i don't have any plans for now...).

**Comment by shillshocked** [comment]
Thanks for all the hard work on this so far. I'll look into those workarounds, but I encourage you when you do the rewrite to look into that. I know I'm not the only user who posts my way, so your program is bound to catch on fast with the masses if you can address popular features such as that one.

**Comment by demanuel** [comment]
Thanks :-)

For that i'll need to rethink of the upload strategy/algorithm... My goal was just to make it uploading fast. I didn't care much for other options. Even the headercheck feature is just a hack, since people were asking for it... Then i started to get more requests like putting a counter in the subject... Well... the code is still manageable, for now :-D
