### ISSUE TITLE
Headersleep issue

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#31]
"Unknown option: headersleep" when specifying these parameters:

-headercheck 1 -headerSleep 20 -retries 10 -headerCheckConnections 25 -uploadsize 640000

Also, I already put all the options in the config file, but if I don't specify -headercheck 1 in the command line, it won't even check the headers.

**Comment by demanuel** [comment]
The option is header**CheckS**leep

For the command line option it's header**C**heck, but you can specify in the conf file like this:

[headerCheck]
enabled= 1
sleep= 20
