### ISSUE TITLE
Error. You have specified 'C' as an Inline programming language.

### ISSUE THREAD

**Issue by maximuml** [demanuel/NewsUP#32]
`~/NewsUP$ perl newsup.pl
Error. You have specified 'C' as an Inline programming language.

I currently only know about the following languages:
    C++, CPP, CXX, Cplusplus, Foo, c++, cplusplus, cpp, cxx, foo

If you have installed a support module for this language, try deleting the
config-x86_64-linux-gnu-thread-multi-5.022001 file from the following Inline DIRECTORY, and run again:

    /NewsUP/_Inline

(And if that works, please file a bug report.)

 at newsup.pl line 40.
BEGIN failed--compilation aborted at newsup.pl line 40.`

**Comment by demanuel** [comment]
Hi!

For the error message it looks like the compiler you set (if you set anything) isn't a valid one.

What compiler and flags are you using? Do you have gcc installed? 

Did you set the environment variables for the compiler?

Did you changed anything in the script or deleted anything? 

Can you remove the Inline folder and try to build again?

**Comment by maximuml** [comment]
Gcc is installed.
No.
No.
Yes, but it's the same.

**Comment by demanuel** [comment]
What OS do you have?

Do you have both Inline and Inline::C installed, right?

What's the version of: 

* perl

* gcc 

* perl module inline::c you have installed (You can check by running: 

perl -M5.010 -e 'require Inline::C; say $Inline::C::VERSION;' 

)

**Comment by maximuml** [comment]
reinstall inline-c and problem solved. Thx.

**Comment by ocean927** [comment]
Execute this 
sudo dnf install 'perl(Inline::C)'
