### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maximuml** [demanuel/NewsUP#33]
Is it any way to see actual uploading speed and etc

**Comment by demanuel** [comment]
Yes, on OS level :-)

Newsup don't display that info. Display only the final speed. It's by design.

**Comment by maximuml** [comment]
Thx. How to do that? How about rar and par creation?

**Comment by demanuel** [comment]
When the posting finishes it will print the final speed as you can see in the wiki page: https://github.com/demanuel/NewsUP/wiki/Upload-Speed


For rar & par creation automatically, you need to use the uploadit script.

Check the readme for more info, or ask here :-)

**Comment by maximuml** [comment]
of course i am using uploadit script for par and rar creation but how to see rar and par creation processs in percents?

**Comment by demanuel** [comment]
I'm sorry but that's not possible.  Something to be done in the future

Enviado do Yahoo Mail para Android 
 
  Em sáb, 21 mai, 2016 às 9:45, maximuml<notifications@github.com> escreveu:   
of course i am using uploadit script for par and rar creation but how to see rar and par creation processs in percents?
