### ISSUE TITLE
newsup.pl line 598.

### ISSUE THREAD

**Issue by maximuml** [demanuel/NewsUP#34]
Read after posting article: 441 435 <197146364416369429.15P5EU7F3A@1FVQVUHLW5.newsup>  at /home/lpbits/NewsUP/newsup.pl line 598.

Is it error?

**Comment by demanuel** [comment]
That means that the post failed.

the codes "441 435" means that the post failed because the article was already uploaded. If you got this while doing the header check then it's normal.

**Comment by maximuml** [comment]
ok
