### ISSUE TITLE
Path issue for _Inline C

### ISSUE THREAD

**Issue by BytesBacon** [demanuel/NewsUP#35]
> Can't create Inline validation file /home/system/media/nzb/intermediate/Release.Name.#729/_Inline/lib/auto/newsup_e934/newsup_e934.inl: No such file or directory at /usr/bin/newsup line 40.
> BEGIN failed--compilation aborted at /usr/bin/newsup line 40.

The path includes "#" character and is making issues.

Also, is there anyway for this _Inline folder to be created once inside the NewsUP folder? And if not, could there be a option to make it a hidden folder (dot vs underscore) with an option oncomplete to auto delete the folder.

**Comment by demanuel** [comment]
Inline needs a place to build your code and to install the results of the build. It uses a single directory named '.Inline/' under normal circumstances. If you create this directory in your home directory, the current directory or in the directory where your program resides, Inline will find and use it. You can also specify it in the environment variable PERL_INLINE_DIRECTORY or directly in your program, by using the DIRECTORY keyword option. If Inline cannot find the directory in any of these places it will create a '_Inline/' directory in either your current directory or the directory where your script resides.

Feel free to delete it at any time. Inline will simply start from scratch and recompile your code on the next run. Please note that it will make the next run slower, as it needs to recompile the code again.

**Comment by BytesBacon** [comment]
`use Cwd;`
`my $inlineBuildDir = Cwd::abs_path(__FILE__).'/_Inline';`
`use Inline C => Config => DIRECTORY => $inlineBuildDir;`

Ended up going this route to fix the issue of having a _Inline folder put in every path where newsup.pl is executed from. It still doesn't fix the issue of having a path with an # character in it. But as long as the location of the NewsUP folder doesn't included # in the path, this will work too and also lock the _Inline folder to the NewsUP folder.

**Comment by demanuel** [comment]
Did you followed the suggestions i gave?

1- Create a .Inline in your home directory or
2- Define the environment variable PERL_INLINE_DIRECTORY.

This way you are going to have only one directory independently from where you invoke it.

This didn't work?

**Comment by BytesBacon** [comment]
Yep that fixes the issue by adding a environment variable or .Inline at the home directory.

However running default without that and an a path including # sign still makes issues. But no reason to fix it, as there are more than one way to fix the problem now, thank you.
