### ISSUE TITLE
NZBs not created correctly

### ISSUE THREAD

**Issue by ldon** [demanuel/NewsUP#36]
When using "perl ~/NewsUP/newsup.pl -comment "dir" -file "dir" the subjects of the NZB created by NewsUP should be like this "This is the first comment [1/1] - "File 1" (AA/BB)" (example 4 from [https://github.com/demanuel/NewsUP/issues/10](url), but it is not, the comment is missing.

Example: Subject in NZB created by NewsUP: "&quot;censored.par2&quot; yEnc (1/1) "
Subject in NZB created by Nzbindex.com/nl: "censored [001/238] - &quot;censored.par2&quot; (1/1)"
This behavior is the same for all subjects in the NZB. 

Note that it is the SAME upload, the NZB differs from the NZB created by Nzbindex.

If you have any further questions, just ask.

**Comment by demanuel** [comment]
Your example seems wrong. Do you mean?
`"perl ~/NewsUP/newsup.pl -comment "This is the first comment" -file "dir" ` 

But you're right. The subject in issue 10 is only for the article uploaded. On the NZB it doesn't use the comments.

Let me check the NZB spec ;-)

I'm marking this as an improvement.

**Comment by ldon** [comment]
Yeah, i am using it in a script and "This is the first comment" should be the dir name, so that i have a subject syntax like that "censored [001/238] - "censored.par2" (1/1)", so dir should be "dir", but you got my point.

I honestly don't know what the NZB spec says but NewsUP generates the NZBs in its own way.

Thank you.

**Comment by demanuel** [comment]
> NewsUP generates the NZBs in its own way

I always wanted NewsUP to be special ;-)

Please check the latest commit.

**Comment by ldon** [comment]
"censored &quot;censored.par2&quot; yEnc (1/1)" is the subject now, the file counter and the hyphen are still missing. (" [AAA/BBB] - "), if you could add these it would be perfect.

**Comment by demanuel** [comment]
oh... I only though that you were complaining only about the missing comment.

I'll fix that later today when i arrive at home.

**Comment by ldon** [comment]
> oh... I only though that you were complaining only about the missing comment.
Sorry for not pointing that out.

If you add this to the subject, it will be identical to the subjects that are posted to Usenet (which should be logical).


Thank you for your effort, great tool.

**Comment by demanuel** [comment]
Please check now the subject in the NZB :-).

It should be fixed.

**Comment by ldon** [comment]
Nice. It is working perfectly for me now. Are the NZBs in the "correct" form if comment 2 is used (Example 6)? If that is implemented similar issues would be avoided.

Thank you, nice work.

**Comment by demanuel** [comment]
Nope. I made it the same way i saw in nzbindex.nl:

`coment 1 [3/5] - "my file.zip" - comment 2 yEnc (1/35).`

According to nzb spec:

> subject 	string - **A slightly munged copy of the article's subject**. The segment counter (xx/yy) usually found at the end, is replaced with (1/yy). You can use the yy to confirm all segments are present.

I don't know what they mean with **A slightly munged copy of the article's subject**, but it's not the same subject as the article uploaded.

To be honest i don't like changing this, because some obscure client might break... I already had in the past complains about some not known clients...

**Comment by ldon** [comment]
Well that

> coment 1 [3/5] - "my file.zip" - comment 2 yEnc (1/35).

way seems to be the right way, i was unfortunately not aware of this. I will close this since the issue is now resolved.

**Comment by demanuel** [comment]
Super! :-)
Any features let me know 
 

    On Monday, May 30, 2016 11:46 PM, ldon <notifications@github.com> wrote:
 

 Well that
coment 1 [3/5] - "my file.zip" - comment 2 yEnc (1/35).
way seems to be the right way, i was unfortunately not aware of this. I will close this since the issue is now resolved.—
