### ISSUE TITLE
Chunk Size / Article Size?

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#4]
How could I go about tweaking the article size and chunk size in your uploader? I typically a chunk size of 1500, 3000 or 5000 depending on content size. So my article sizes are 192000, 384000 and 640000 respectively. In order to maintain efficient transmission, how can I adjust the uploader to account for this?

**Comment by demanuel** [comment]
There's no configuration option for this. So to do this you need to edit the file lib/Net/NNTP/Uploader.pm
and change the variable ```$NNTP_MAX_UPLOAD_SIZE```, line 18.

**Comment by shillshocked** [comment]
Yeah I noticed that, but it was a bit confusing. You have three lines referencing that:

#750Kb - the segment size. I tried with 4 Megs and got a 441. The allowed posting segment size isn't standard
our $NNTP_MAX_UPLOAD_SIZE=512*1024; 
my $YENC_NNTP_LINESIZE=128;

Which number is the chunk size, and which is the article size?

**Comment by demanuel** [comment]
What do you mean with article size? I can't predict what will be the size of the article, before yenc it.

The $NNTP_MAX_UPLOAD_SIZE is the size of the segments. It will read $NNTP_MAX_UPLOAD_SIZE bytes of the file and yenc them.

The $YENC_NNTP_LINESIZE is the line size of the article, used on yenc:
```
To facilitate transmission via existing standard protocols (most notably
NNTP), carriage return/linefeed pairs should be written to the output
stream after every n characters, where n is the desired line length.  
Typical values for n are 128 and 256.
```
from yenc spec at: http://www.yenc.org/yenc-draft.1.3.txt

**Comment by shillshocked** [comment]
Must just be differences of terminology. Yeah, 5000 * 128 = 640000, so 128 is the yenc line size and max upload size would be gopoststuff's article size.

**Comment by shillshocked** [comment]
Any way to make this a configurable option on the command line, seeing as how different values tend to work better with different file size ranges?

**Comment by demanuel** [comment]
Please checkout the last version.

Added -uploadsize switch. 
Example:
```
perl newsup.pl -f file_to_upload -uploadsize 192000
```

**Comment by shillshocked** [comment]
Okay, looks great! But in the documentation, that should be size in bytes, not kilobytes.

**Comment by demanuel** [comment]
Yes. Nice catch! Let me correct the documentation
