### ISSUE TITLE
use switch for subject (like newsmangler or gopoststuff)

### ISSUE THREAD

**Issue by ERR1R** [demanuel/NewsUP#43]
Hi,

is it possible you could add a switch so you could use a subject like mangler or gopoststuff

**Comment by demanuel** [comment]
Isn't the option -comment enough?

The subject of uploaded files need to follow some pattern. If you want me to change or add a new feature, can you provide some examples on how to use it?

**Comment by ERR1R** [comment]
i use this line with gopoststuf in my script:

$GoPostStuff -c $config -s "${postname%.*}" "$checkpath/$releasedir/"

outputs: 

**7135cd949635183c92f5cb458c191825 [1/61] - "7135cd949635183c92f5cb458c191825.01" yEnc**

first part is the subject and second part are the files.. -comment is not doing the same is it?

**Comment by demanuel** [comment]
The comment switch will do what you need :-)

Please check [here for more info](https://github.com/demanuel/NewsUP/issues/10)

**Comment by ERR1R** [comment]
ahhh... it was confusing! Sorry about that! 

Why not name it _subject_ like all other posters?  :-D

**Comment by demanuel** [comment]
because it's a "comment" in the subject :-)
