### ISSUE TITLE
put Header check in background

### ISSUE THREAD

**Issue by ERR1R** [demanuel/NewsUP#45]
Hi,

So i just tested the newsup.pl you linked to.. Works fine indeed! 
But, was wondering if its possible to put the header check in the background.

I post with a script and use inotify-tools to monitor a directory.. So when the script posts to a server its possible another upload is queued. When the upload is finished the script will continue to post the queued one.  If i use header checking with 30 minutes, the script will have to wait for 30 minutes to start the next upload.

**Comment by demanuel** [comment]
It's not possible for the simple reason:
*- To do the headercheck you need to have the segments in memory in case you need to re-upload them. If that was possible with muliple uploads the memory would just keep increasing during those 30 mins. This would cause problem in lower end computers.

My suggestion to achieve something similar is:

There's a script completion_checker.pl that's distributed in the scripts folder. This script gets an NZB as parameter. You can do your uploads normally without headercheck, and later you can run that script against your nzbs.

If there are segments missing, you can re-up the file. Would that be good for you?

**Comment by ERR1R** [comment]
Hi,

I found the script!  this is ok.. i could run that in the background in bash in my script.
