### ISSUE TITLE
Speed output?

### ISSUE THREAD

**Issue by ERR1R** [demanuel/NewsUP#48]
Would be nice if there is some speed output.. Sometimes a provider is going nuts and speed is about zero.. 
Now you cant see speed output so you never now how fast it goes..

**Comment by demanuel** [comment]
I'm not going to implement this. 

Perl is very slow for doing math, that's the reason yenc encoding is done in C (as initially was in perl).

This might affect the overall upload speed. If you want or you need to know the current upload speed you can use:

### Windows

- Task manager
### Linux
- bwm-ng 
- speedometer (speedometer -t eth0 -s )
- gkrellm
- conky
