### ISSUE TITLE
add nfo file to par set

### ISSUE THREAD

**Issue by larryy** [demanuel/NewsUP#59]
Love the new --nfo feature. With the recent improvements you've made it is now possible to issue a single command to do a well configured upload. Thank you!

One minor suggestion / request: Even though it is great that the nfo file is not included in the rar set (so standard nzb search engines can find and display it on its own), it would be nice if it *was* added to the par set, so if it is missing it can be reconstructed from the par2 files. This is by far the most common way to handle nfo files and par sets, in my experience. And I think it is as easy as adding the nfo file path to the end of the par2 command line.

**Comment by demanuel** [comment]
implemented :-)

**Comment by larryy** [comment]
Awesome! Major thanks!
