### ISSUE TITLE
Different server to perform the headercheck, than the server used to upload the articles

### ISSUE THREAD

**Issue by demanuel** [demanuel/NewsUP#6]
A new functionality of having a different server to check the header, instead of the server used to upload.

**Comment by demanuel** [comment]
There's now the options:
headerCheckServer, headerCheckPort, headerCheckUser and headerCheckPassword

**Comment by demanuel** [comment]
Implemented.

**Comment by shillshocked** [comment]
Not sure if this is working as intended. I got incompletes from my headercheck server showing on my news client, yet the header check when through okay in the software.

**Comment by demanuel** [comment]
Hmmm... Strange. I'll have a look later on the day. I'll provide you a debug version, that you'll need to run.

Does that happens only when you use a different headercheck server? If you try to download from the server where you upload the stuff, is it ok?

Are you passing the headercheck server through command line or configuration file? 
Can you paste here the section headercheck from your configuration file?

**Comment by shillshocked** [comment]
Here is my config:

[server]
server= upload.server1.com
port= 119
connections= 10

[auth]
user= server1user
password= server1pass

[metadata]
client= NewsUP

[upload]
uploader= UPLOADER <UPLOADNAME@HOST.COM>
newsgroup= alt.binaries.something

[headercheck]
enabled= 1
sleep= 0
server= upload.server2.com
port= 119
user= server2user
password= server2pass

[generic]
tmp = /tmp
randomize= 0
monitoringPort = 8675


[other]
############################
#
# Variables
############################
# Path to newsup script
PATH_TO_UPLOADER=~/bin/NewsUP-master/newsup.pl
# Extra arguments to newsup
EXTRA_ARGS_TO_UPLOADER=
# RAR compression level
ENABLE_RAR_COMPRESSION=0
# Path to RAR
PATH_TO_RAR=/usr/bin/rar
# Extra options to RAR  
EXTRA_ARGS_TO_RAR=a -m0 -v10M -ep -vn -ed -r
# Enable SFV generation
ENABLE_SFV_GENERATION=0
# Path to PAR2
PATH_TO_PAR2=/usr/bin/par2
#Extra options to par2 repair program
EXTRA_ARGS_TO_PAR2=c -r10
# Enable PAR archives creation
ENABLE_PAR_CREATION=0
# Folder to where the scripts files should be written
# It's obigatory to terminate on the separator folder char.
TEMP_DIR=/tmp/
# Randomize Names
# The names are toggled
RANDOMIZE_NAMES=0

**Comment by shillshocked** [comment]
Tried it with my upload server in the headercheck settings, and it took no time to do the header check. That server lags, so my only conclusion can be that it's not header checking.

**Comment by demanuel** [comment]
Strange... I'm looking to the code and not seeing anything wrong.
Anyway i added output messages. Can you try this version: https://github.com/demanuel/NewsUP/archive/6.zip 

?

**Comment by shillshocked** [comment]
It appears to be working now in this version..

**Comment by demanuel** [comment]
Strange because i didn't do anything... I just put the script writing to the output when performing the headercheck.

Is the behaviour different when the running the branch 6 from the master branch?

**Comment by shillshocked** [comment]
Yeah, at least it appeared so... no idea why.

**Comment by demanuel** [comment]
I'm closing this as i can't reproduce it. Feel free to reopen it ;-)
