### ISSUE TITLE
I'm getting an error with the latest build

### ISSUE THREAD

**Issue by peaveyman** [demanuel/NewsUP#60]
Article posting failed: 441 Posting Failed. "From" Header not in Internet Syntax. E1
Stopping download! Please check the error message above!

Here is my conf file:

[server]
server= *****
port= 563
connections= 5
tls = 1
tls_ignore_certificate = 0
# To generate random ids or to use the returned ones from the server. Note: Some servers don't return anything. In that case change this option to 1
generate_ids = 0 

[auth]
user= ****
password= *****

[upload]
uploader= Peaveyman <News@Newsconnection.local>
newsgroups= alt.binaries.sounds.lossless.country, alt.binaries.sounds.flac, alt.binaries.sounds.lossless
obfuscate = 0
# default value 750KBytes
size = 768000

[headerCheck]
enabled= 1
sleep= 20
retries= 3
connections = 3
server = ****
port = 563
user = ****
password = ****

[metadata] 
#You can put here anything you want to appear on the nzb header. It must have the pattern: word= a big one line sentence
client= NewsUP
veryWeirdInfoIWantToPutOnTheNZBMetadata= its really very weird!

[extra-headers]
#extra header. It will became X-extra-header
extra-header= value1
#extra header. Non valid because there's already one
X-extra-header= value3
#second extra header
extra-header2= value2 
#non valid. Non valid headers are: from, newsgroups, message-id and subject.
from= test 

[options]
splitnpar= 0
# Command that will be used to generate the splitted files
# For rar files use:
# rar a -m0 -v50m -ed -ep1
split_cmd = 7z a -mx0 -v50m -t7z --
# pattern of the files generated with the split_cmd.
# If splitnpar is set to 1, these are the files that
# are going to be uploaded.
# For rar files use: 
# *rar
split_pattern = *7z *[0-9][0-9][0-9]
par2 = 0
# full path to par2 executable
par2_path = par2
# this will be used if you use the obfuscation option
par2_rename_settings = c -s768000 -r0
par2_settings = c -s768000 -r15
temp_folder = /home/gary/tmp
# if the nzb is also uploaded
upload_nzb = 1 
nzb_save_path = /home/gary/uploads/

**Comment by peaveyman** [comment]
I downgraded newsup and it's posting now but I am getting this after it posts each part:

Warning: Read after posting article: 240 Article Posted

**Comment by demanuel** [comment]
Thanks for the report.

I will take a look.

Btw, how did you downgraded?

**Comment by peaveyman** [comment]
I have several of the packages saved on my computer. I run Manjaro which is an arch spin off. I just used pacman -U to install the one I wanted.

**Comment by peaveyman** [comment]
I even tried changing the newsgroups= to newsgroup= but that didn't work either.

**Comment by peaveyman** [comment]
Any word on this problem?

**Comment by demanuel** [comment]
yes, i was able to reproduce the issue. On my system, It happens once in 15 uploads, or so...

Still debugging.

**Comment by peaveyman** [comment]
Give me a minute and I will get back to you.

**Comment by peaveyman** [comment]
It's uploading now. THANKS!!!

**Comment by demanuel** [comment]
Nice. 
Please feel free to close it when you are confident it's fixed.

**Comment by peaveyman** [comment]
I will. Let me ask this. At the end of the first upload after the header check I got this message. Is it something to worry about?

Can't call method "message_id" on an undefined value at /usr/bin/vendor_perl/newsup line 258

**Comment by demanuel** [comment]
It's a bug, but is something minor. Please make sure that you have the option on your config file:

[server]
generate_ids = 1

**Comment by peaveyman** [comment]
I didn't. I do now. I will upload another and see what it does.

**Comment by peaveyman** [comment]
I changed the value and now when I start an upload I get this:

Article posting failed: 441 Posting Failed. Required "Subject" Header is missing E1

Changing the value back to 0 lets the upload continue.

**Comment by nonspin** [comment]
> uploader= Peaveyman `<News@Newsconnection.local>`

Isnt the syntax incorrect ? 
More Like -> `user (email@domain)`

.. if `<>`  you'd need to wrap `&#34;` or `""` ?

Like: `&#34;Peaveyman <News@Newsconnection.local>&#34;`

... and if specified >from= test
would break it, wouldn't it ?

**Comment by peaveyman** [comment]
I just tested the newest version and all seems well. I am closing this now.

**Comment by demanuel** [comment]
@nonspin 

That's on the extra-headers config. The mandatory headers cannot be specified in the extra-headers section as they will be ignored: https://github.com/demanuel/NewsUP/blob/master/lib/NewsUP/Article.pm#L295

The From: header is specifed in:
```
[upload]
uploader= NewsUP <NewsUP@somewhere.cbr>
```

The from header is specified in: https://tools.ietf.org/html/rfc1036

**Comment by nonspin** [comment]
Well, that's true as long as: 
`obfuscate=0`
Try
`obfuscate=1`

**Comment by demanuel** [comment]
@nonspin 

I'm unable to reproduce that issue.

Added:

    [extra-headers]
    from= test

And enabled the obfuscation: 
    
    [upload]
    obfuscate = 1

And did the upload and everything went normal:

    From: lLTFUbrZ1 <xY724tvi0VUgE@OqTK3V.2kn>

Are you using the latest version? If not can you do a backup of your version and then try the latest one?

**Comment by nonspin** [comment]
I'll run some more tests, because i've found  some irritations..
if obfuscate=1
"uninitialized file_size" in (/) division .. could be PERL issue on my machine.

p.s.: All task complete successfully (tested) - I'll  get back to you.

**Comment by demanuel** [comment]
Can you tell me the full error message:
> "uninitialized file_size" in (/) division ..
