### ISSUE TITLE
Obfuscation [request]

### ISSUE THREAD

**Issue by nonspin** [demanuel/NewsUP#62]
The obfuscation of  the subject in the <file> tag is very incompatible with some downloaders (ex. newsleecher)
because the (1/parts) is not present after the filename in the -> created __nzb__

An obfuscated subject like:
`subject="&#34;[OBFUSCATED_FILENAME]&#34; yEnc (01/xx)"`
would be very nice - for the .nzb that is.

`&#34; or &quot;`

**Comment by demanuel** [comment]
Do you mean on the actual post or on the NZB?
Can the values be bogus, like "(32/43)"?

**Comment by demanuel** [comment]
Well, you have to break yenc spec (i tried to break the least) if you want to have real obfuscation and Nzbget and SABNZB can process those files :-)

I'll create a branch that will add some bogus numbers, and let's see.

**Comment by demanuel** [comment]
[Can check this branch?](https://github.com/demanuel/NewsUP/tree/nospin)

**Comment by nonspin** [comment]
I'm not going in too deep and you can delete the branch and the request..

utils.pm LN283
```
if ($options->{OBFUSCATE}) {
            $fileElement->setAttribute('subject' => generate_random_string(64) . " yEnc (1/@{[int(rand(100))]})");
        }
```
.. " Double-Quotes needed for separation " like i said three times and i really don't know why
the random number was added.

proper: 
```
if ($options->{OBFUSCATE}) {
            $fileElement->setAttribute('subject' => '"' . generate_random_string(64) . '" yEnc (1/' . scalar(@{$fileMapping{$filename}}) . ')');
        }
```

To wrap-up the rest:
-> On Windows 
If -f points to a folder like '.\test\' or a single file like '.\test\file.rar' , 
not only do you get: (ALWAYS)
```
You must specify a list of files when creating.
Use of uninitialized value $file_size in division (/) at .\bin\newsup.pl line 304.
Use of uninitialized value $file_size in addition (+) at .\bin\newsup.pl line 305.
```
- it does upload everthing properly and finish all tasks
- but messes with the nzb-name/path 

- the created subfolder in /temp/ is not removed afterwards (just the folder)

Appreceated though

**Comment by demanuel** [comment]
> .. " Double-Quotes needed for separation " like i said three times
[This is the NZB, not the yenc post. No escaped quotes in the middle should be required](https://sabnzbd.org/wiki/extra/nzb-spec.html)

>  i really don't know why the random number was added.
Because the point is obfuscation. If random number works, then i'm fine with it and i'll merge it in master, otherwise If some client don't understand it  i prefer not to implement it because defeats the obfuscation. 
Anyway that it was what i said i was going to do:
>  I'll create a branch that will add some bogus numbers, and let's see.

:-)

> On Windows
> ...
Thanks i'll try to have a look, but first i need to get a windows VM.
Meanwhile i have questions regarding this:

1. If you use forward slashes ('/') like "newsup -f ./test/", does it work? (windows supports forward slashes but probably tyou need to put under quotes)

2. If you pass the full path (c:/path/to/file/test.rar) the behaviour remains the same?

3. What's the windows version?

**Comment by nonspin** [comment]
> Because the point is obfuscation.

it's the .nzb for crying out loud. Obfuscation only makes sense, if the .nzb
is passed on to the indexer - and NOT uploaded with the files.
Sitting right next to it .. 

The obfuscation is mostly done locally (filenames) after creating the par2's
and to the Message-IDs . Scattering the files over multiple groups would do the rest.
If you want to go the extra mile, randomize the archive (rar) sizes during creation.
10x50MB (or 7x15) no matter - no obfuscated - kind of stick out, right ?
 
Now, whoever has the .nzb - obfuscated or not - has all the pieces anyway,
no matter how obfuscated ... don't you see that ? 
The goal is to NOT leave a obvious pattern behind ...

That's how my files look like locally, 
using (rar) "-v" creating random slices depending on the overall size.
- basename.rar through .r06
- Create Par2's 
- Renaming the rar's with this:

Powershell:
``` Powershell
$obfusc = -join ([char[]](65..90 + 97..122) * 100 | Get-Random -Count (Get-Random -Minimum 12 -Maximum 24))
        Copy-Item -Path $_.FullName -Destination ('temp\' + $obfusc.TrimStart(".").TrimEnd(".") ) 
        }
``` 
 
result:
```
CorYHIHFambb	96,967,575	
mtdNQdkgQuWKGtyuPYJSQ	69,206,016	
jnROajiOTsfpJEw	63,963,136	
lculJCEhuyOf	70,254,592	
CpxiSiDNvdwkEkXqmh	75,497,472	
YMHBxDlkAOJGWDQHryilhFh	55,574,528
```
.. plus the .par2-VolSet	

Now why would you further obfuscate anything .. like the the nzb-subject ?
Logically, your nzb-subject would be the ORIGINAL filename (pre-par2),
because you don't upload it (nzb) and pass it on to the indexer.

If you scatter the files over multiple groups and rotate the Message-IDs
(NOT randomizing it) -> "..-nyuu", "..-PowerPost", "..-NewsUp"...
that's it - At least, that's how you'd do it after thinking it through ?!

Messing with the Par2-Names is a No-No and the -r0 rename stunt
breaks most clients. .. and also not necessary, if you'd think it through..

I can send you some scripts that may shine some light on it...

and the name is nonspin

**Comment by demanuel** [comment]
> Scattering the files over multiple groups would do the rest.

That is being done already :-)

> randomize the archive (rar) sizes during creation. 10x50MB (or 7x15) - no matter how obfuscated - kind of stick out, right ?

That's a good idea! I like it.

> 10x50MB (or 7x15) - no matter how obfuscated - kind of stick out, right ?

Obfuscation by lots of people uploading the same sizes?

> Now, whoever has the .nzb - obfuscated or not - has all the pieces anyway, no matter how obfuscated ... don't you see that ?

You're right. But having a different name on the NZB than on the post it might give more trouble to automated bots (i can just hope)

> using (rar) "-v" creating random slices depending on the overall size.

I could inject a "-v <random_value>" on the rar invocation, but then it would stop being application agnostic (as it should support, at least, 7zip as well). 

> Now why would you further obfuscate anything .. like the the nzb-subject ? Logically, your nzb-subject would be the ORIGINAL filename (pre-par2), because you don't upload it (nzb) and pass it on to the indexer.

It makes sense **to not** upload the NZB when the obfuscation is taking place. I'll change that. There's no point in having the original filenames in the NZB as the upload contains the renaming par.

**Comment by demanuel** [comment]
> so these are the changes that i'm going to implement:
> 
>     Add the counter in the subject
> 
>     remove the nzb upload when the obfuscation is taking place. (It's not doing anything user functionality wise)
> 

Done. Please check master.

**Comment by demanuel** [comment]
Can i close this?

**Comment by demanuel** [comment]
No changes regarding this for more than a last year. Please feel free to re-open it.
