### ISSUE TITLE
Errors with new version

### ISSUE THREAD

**Issue by peaveyman** [demanuel/NewsUP#73]
I am getting this error when trying to use the new version:

Can't locate File/Copy/Recursive.pm in @INC (you may need to install the File::Copy::Recursive module) (@INC contains: /home/gary/uploads/_Inline/lib /usr/bin/vendor_perl/../lib /usr/lib/perl5/5.28/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.28/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.28/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/vendor_perl/NewsUP/Utils.pm line 17.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/NewsUP/Utils.pm line 17.
Compilation failed in require at /usr/share/perl5/vendor_perl/NewsUP/Article.pm line 5.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/NewsUP/Article.pm line 5.
Compilation failed in require at /usr/bin/vendor_perl/newsup line 7.
BEGIN failed--compilation aborted at /usr/bin/vendor_perl/newsup line 7.

**Comment by demanuel** [comment]
You need to install the perl module File::Copy::Recursive

Depending on the distro you have the name of the package is:

For ubuntu, libfile-copy-recursive-perl
Arch: perl-file-copy-recursive
Suse: perl-File-Copy-Recursive

**Comment by peaveyman** [comment]
Thanks. It's working now.

**Comment by demanuel** [comment]
dependency added to PKGBUILD
