### ISSUE TITLE
debian stretch with perl 5.24 only

### ISSUE THREAD

**Issue by iconmix** [demanuel/NewsUP#74]
hello....i'm on debian 9 stretch ....
but perl version can't be upgraded to 5.26 :(

`Clonage dans 'NewsUP'...
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 2067 (delta 27), reused 56 (delta 20), pack-reused 1990
Réception d'objets: 100% (2067/2067), 232.63 MiB | 9.62 MiB/s, fait.
Résolution des deltas: 100% (944/944), fait.
fatal: Ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git
awk: fatal : impossible d'ouvrir le fichier « ./bin/newsup.pl » en lecture (Aucun fichier ou dossier de ce type)
MATCH
--2019-06-27 11:19:26--  https://gist.githubusercontent.com/demanuel/87e0eac62dd6d0919031131dd8fbad3d/raw/2a9a9db3694c8622b1fb06d5a880db1fa3a62230/newsup.526.patch
Résolution de gist.githubusercontent.com (gist.githubusercontent.com)… 151.101.120.133
Connexion à gist.githubusercontent.com (gist.githubusercontent.com)|151.101.120.133|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 2329 (2,3K) [text/plain]
Sauvegarde en : « newsup.526.patch »

newsup.526.patch                                  100%[==========================================================================================================>]   2,27K  --.-KB/s    in 0s

2019-06-27 11:19:26 (29,2 MB/s) — « newsup.526.patch » sauvegardé [2329/2329]

patching file Utils.pm
Hunk #2 succeeded at 17 (offset 1 line).
Hunk #3 succeeded at 585 (offset 10 lines).
Hunk #4 succeeded at 594 (offset 10 lines).
Hunk #5 succeeded at 663 (offset 10 lines).
dpkg-deb: building package 'newsup' in 'newsup.deb'.
Sélection du paquet newsup précédemment désélectionné.
(Lecture de la base de données... 153162 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de newsup.deb ...
Dépaquetage de newsup (5.26) ...
dpkg: des problèmes de dépendances empêchent la configuration de newsup :
 **newsup dépend de perl (>= 5.26) ; cependant :
  La version de perl sur le système est 5.24.1-3+deb9u5.**

dpkg: erreur de traitement du paquet newsup (--install) :
 problèmes de dépendances - laissé non configuré
Des erreurs ont été rencontrées pendant l'exécution :
 newsup
`
if there any solution to install newsup with perl 5.24 ?
thank you

**Comment by demanuel** [comment]
:-S

I'm thinking of updating to perl 5.30 XD

I guess i need to create a another script specific for debian...

I haven't tried this, but if you change these two lines from 5.26 to 5.24:
1- https://github.com/demanuel/NewsUP/blob/master/build_scripts/ubuntu/ubuntu.sh#L19
2- https://github.com/demanuel/NewsUP/blob/master/build_scripts/ubuntu/ubuntu.sh#L22

Does it work?

**Comment by demanuel** [comment]
@iconmix I just updated the script. Now it's named debian.sh and it should work on all debian based systems.

I tried on debian 9.9 and it work. 

Please run it again :-)

**Comment by z0rti** [comment]
Doesn't work on ubuntu 19.04 disco ;-/

```
The perl right version to run this program is: 5.30
You have 5.28
[...]
Installation successfull!

```
but then
```
$ newsup                                                                                                                        
Perl v5.30.0 required--this is only v5.28.1, stopped at /usr/local/bin/newsup line 2.
BEGIN failed--compilation aborted at /usr/local/bin/newsup line 2.

```

**Comment by demanuel** [comment]
My fault, i forgot to change a hardcoded value in the debian.sh when i updated to version 5.30
Can you please check now again?

    On Saturday, July 6, 2019, 4:16:41 PM GMT+2, z0rti <notifications@github.com> wrote:  
 
 
Doesn't work on ubuntu 19.04 disco ;-/
The perl right version to run this program is: 5.30
You have 5.28
[...]
Installation successfull!


but then
$ newsup                                                                                                                        
Perl v5.30.0 required--this is only v5.28.1, stopped at /usr/local/bin/newsup line 2.
BEGIN failed--compilation aborted at /usr/local/bin/newsup line 2.

**Comment by z0rti** [comment]
> My fault, i forgot to change a hardcoded value in the debian.sh when i updated to version 5.30 Can you please check now again?

It does work now, thx!

On Ubuntu 19.04 disco i had to install these packages:

`
$ apt install bc git patch wget curl gcc make perl libio-socket-ssl-perl libnet-ssleay-perl libxml-libxml-perl libfile-copy-recursive-perl libconfig-tiny-perl libinline-c-perl
`

**Comment by demanuel** [comment]
> It does work now, thx!

Good to know! :-D

> On Ubuntu 19.04 disco i had to install these packages:
>
> $ apt install bc git patch wget curl gcc make perl libio-socket-ssl-perl libnet-ssleay-perl libxml-libxml-perl libfile-copy-recursive-perl libconfig-tiny-perl libinline-c-perl

Btw, the aplications bc, git, patch, wget and curl, are only needed to build the package. After you have the package build, you don't need them anymore.

**Comment by demanuel** [comment]
Closing this. Please feel free to re-open it.
