### ISSUE TITLE
Error when using option -skipcopy

### ISSUE THREAD

**Issue by z0rti** [demanuel/NewsUP#75]
I want to skip the copying into the temp_folder (because unnecessary)
The files are in ./upme/*

```
$ newsup -f upme -skipcopy
You must specify a list of files when creating.
```

this is an error output from 'par2'
the $cmd generated is:

`par2 c -s768000 -r15 /29iSXFiZfzTj "upme"`

so the temp_folder is not used for the target par2, 
and "folder" is not a valid option, it has to be "folder"/* (or the file list)

(also there seems to be no error handling, if par2 fails)

**Comment by demanuel** [comment]
Thanks for the report. I'm trying to reproduce it without success.

Can you tell me what options are you using? Please let me know the options splitnpar, par2, skipcopy 

btw, par2cmdline can be tricky when generating the files on different paths.

Opened #79 to track error handling of external commands

**Comment by z0rti** [comment]
I'm using just this:
splitnpar=0
par2=1
```
$ newsup -f upme --noNzb --skipCopy
You must specify a list of files when creating.

```

Oh! I just found out it does work when i do
`$ newsup -f upme/* --noNzb --skipCopy`

It then saves the *par2 files in upme/
Tricky as in 'impossible' to save par2 files in a different dir i guess ;-/

**Comment by demanuel** [comment]
Please check the latest commit. Let me know if something is not working correctly.

**Comment by demanuel** [comment]
Closing it as there's no update. Feel free to re-open it.
