### ISSUE TITLE
_Inline folder is created

### ISSUE THREAD

**Issue by z0rti** [demanuel/NewsUP#76]
Every time i run newsup it creates a folder named '_Inline' in the current dir.
If that is actually needed i suggest using /tmp/ for it ;)

**Comment by demanuel** [comment]
Inline needs a place to build your code and to install the results of the build. It uses a single directory named '.Inline/' under normal circumstances. If you create this directory in your home directory, the current directory or in the directory where your program resides, Inline will find and use it. You can also specify it in the environment variable PERL_INLINE_DIRECTORY. If Inline cannot find the directory in any of these places it will create a '_Inline/' directory in either your current directory or the directory where your script resides.

Feel free to delete it at any time. Inline will simply start from scratch and recompile your code on the next run. Please note that it will make the next run slower, as it needs to recompile the code again.


Updated the readme with that information.

Please also check #35 and #30 

Let me know if you have any other question regarding this.

**Comment by z0rti** [comment]
Got it, thx. Sorry, i didn't search the closed issues...
