### ISSUE TITLE
Header check delay

### ISSUE THREAD

**Issue by peaveyman** [demanuel/NewsUP#8]
The default delay is set to 20. Is this seconds, minutes or what?

**Comment by demanuel** [comment]
It's in seconds.
 


     On Thursday, July 2, 2015 2:30 PM, peaveyman <notifications@github.com> wrote:
   

 The default delay is set to 20. Is this seconds, minutes or what?—

**Comment by peaveyman** [comment]
Yeah, if I had bothered to read the readme file I would have seen that. This can be closed.

**Comment by demanuel** [comment]
:-)
