### ISSUE TITLE
NewsUP can't handle files with '('

### ISSUE THREAD

**Issue by maximuml** [demanuel/NewsUP#80]
par2 c -s768000 -r18 
folder (2019) 
"folder (2019).part2.rar"
"folder (2019).part3.rar" 
"folder (2019).part1.rar"

sh: -c: line 0: syntax error near unexpected token `('

sh: -c: line 0: `par2 c -s768000 -r18 
folder (2019) 
"folder (2019).part2.rar"
"folder (2019).part3.rar" 
"folder (2019).part1.rar"'

sh: -c: line 0: syntax error near unexpected token `('Use of uninitialized value $read in pattern match (m//) at /usr/local/bin/newsup line 538.

Any help?

**Comment by demanuel** [comment]
Done. It should be fixed. Can you update your version?

**Comment by maximuml** [comment]
Fixed

**Comment by maximuml** [comment]
Fixed
