### ISSUE TITLE
Switch from par2 to parpar

### ISSUE THREAD

**Issue by maximuml** [demanuel/NewsUP#81]
is it any way to switch from par2 to parpar?
ParPar is a high performance, multi-threaded PAR2 creation tool and library for node.js. ParPar does not verify or repair files, only creates redundancy. ParPar is a completely new, from ground-up, implementation, which does not use components from existing PAR2 implementations.
benchmark comparisons - https://github.com/animetosho/ParPar/blob/master/benchmarks/info.md
Thanks!!!!

**Comment by demanuel** [comment]
Yes it is possible. For you to use parpar you need to change the options in the config file:

- par2path

Change this option to where you have the parpar binary

- par2_rename_settings

Change this option with the switches required for creating the renaming pars (not required if you don't use obfuscation)

- par2_settings

Change this option with the switches required to create the par2 files.

The par command is invoked in this way:
`${par2_path} ${par2_settings} ${output} ${input}`

please note that:
`${output}` and `${input}` are automatic (no way to change) and filled by newsup 

You'll have to find the right options yourself.

**Comment by maximuml** [comment]
Thanks

**Comment by maximuml** [comment]
Switched from par2cmd to ParPar. ParPar is much faster
New command line is '-d pow2 -s 2M -r19% -o'

**Comment by demanuel** [comment]
@maximuml 

Would be a correct example:

`parpar d pow2 -s 2M -r20% -o /path/to/file.par2 /path/to/rar1.rar /path/to/rar2.rar` ?

I will update the default configuration file with your findings

**Comment by maximuml** [comment]
Yes.
Lines in my config file is
par2_path = parpar
par2_settings = -d pow2 -s 2M -r19% -o

**Comment by demanuel** [comment]
Thank you
