### ISSUE TITLE
Show process of creating archives RAR

### ISSUE THREAD

**Issue by maximuml** [demanuel/NewsUP#82]
Is It any way to show it?? Thx

**Comment by demanuel** [comment]
Check the latest version :-)

Just run with "--debug"

**Comment by maximuml** [comment]
Thanks, i will test it later

**Comment by maximuml** [comment]
Wow, so much info. I just need rar, par creation and uploading

**Comment by demanuel** [comment]
It just prints the options you are using, and then all the external processes and respective that are invoked.

**Comment by maximuml** [comment]
too much information. I just need to see how much time each process takes and at what stage it is now

**Comment by demanuel** [comment]
The last commit should show at which stage newsup is.

**Comment by maximuml** [comment]
Thanks
