### ISSUE TITLE
ipv6 usenet server error

### ISSUE THREAD

**Issue by maximuml** [demanuel/NewsUP#84]
Error: Failed to connect to eunews-v6.blocknews.net:119: Invalid argument [IO::Socket::INET: Bad hostname 'eunews-v6.blocknews.net'] at /usr/local/bin/newsup line 636.

**Comment by demanuel** [comment]
What's the IO::Socket::INET version that you have?

**Comment by maximuml** [comment]
dll:~$` nslookup eunews-v6.blocknews.net

Server:         213.186.33.99
Address:        213.186.33.99#53

Non-authoritative answer:
eunews-v6.blocknews.net canonical name = blocknews-fr6.sslusenet.com.
Name:   blocknews-fr6.sslusenet.com
Address: 2001:4de0:3:119::80

@dll:~$ ping eunews-v6.blocknews.net
PING eunews-v6.blocknews.net(2001:4de0:3:119::80 (2001:4de0:3:119::80)) 56 data bytes
64 bytes from 2001:4de0:3:119::80 (2001:4de0:3:119::80): icmp_seq=1 ttl=56 time=193 ms
64 bytes from 2001:4de0:3:119::80 (2001:4de0:3:119::80): icmp_seq=2 ttl=56 time=127 ms
64 bytes from 2001:4de0:3:119::80 (2001:4de0:3:119::80): icmp_seq=3 ttl=56 time=178 ms
64 bytes from 2001:4de0:3:119::80 (2001:4de0:3:119::80): icmp_seq=4 ttl=56 time=181 ms
64 bytes from 2001:4de0:3:119::80 (2001:4de0:3:119::80): icmp_seq=5 ttl=56 time=130 ms
^C
--- eunews-v6.blocknews.net ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 127.398/162.304/193.630/27.595 ms

**Comment by demanuel** [comment]
This is going to take a while to figure it out, as i don't have ipv6 enabled. For now you need to use ipv4 addresses.

**Comment by maximuml** [comment]
https://www.perl.org/about/whitepapers/perl-ipv6.html
> To enable IPv6 in Perl, replace any use of IO::Socket::INET with IO::Socket::IP

**Comment by demanuel** [comment]
I'm unable to test, as i my ISP don't have IPv6 enabled (According to the answer i got, they are on a roll-out plan that will take them approx. 2 years).

i did the changes, but i'm unable to check if it is working. Please the latest master, and let me know if everything's fine.



Meanwhile reading the documentation of [IO::Socket::SSL](https://metacpan.org/pod/IO::Socket::SSL) i found the following:

> IO::Socket::SSL inherits from another IO::Socket module. The choice of the super class depends on the installed modules:
> 
> If IO::Socket::IP with at least version 0.20 is installed it will use this module as super class, transparently providing IPv6 and IPv4 support.
> 
> If IO::Socket::INET6 is installed it will use this module as super class, transparently providing IPv6 and IPv4 support.
> 
> Otherwise it will fall back to IO::Socket::INET, which is a perl core module. With IO::Socket::INET you only get IPv4 support.
> 

So for SSL connections you should be covered with IPV6.

**Comment by maximuml** [comment]
Fixed
