### ISSUE TITLE
Error with last build

### ISSUE THREAD

**Issue by maximuml** [demanuel/NewsUP#85]
Can't locate NewsUP/Article.pm in @INC (you may need to install the NewsUP::Article module) (@INC contains: /usr/local/bin/../lib /home/111/perl5/perlbrew/perls/perl-5.31.6/lib/site_perl/5.31.6/x86_64-linux /home/111/perl5/perlbrew/perls/perl-5.31.6/lib/site_perl/5.31.6 /home/111/perl5/perlbrew/perls/perl-5.31.6/lib/5.31.6/x86_64-linux /home/111/perl5/perlbrew/perls/perl-5.31.6/lib/5.31.6) at /usr/local/bin/newsup line 7.
BEGIN failed--compilation aborted at /usr/local/bin/newsup line 7.

**Comment by demanuel** [comment]
How are you installing newsup?

On my arch machine works ok. Are you using ubuntu/debian?

**Comment by demanuel** [comment]
How are you installing newsup?

On my arch machine works ok. Are you using ubuntu/debian?

**Comment by maximuml** [comment]
Ubuntu 18.04 
Install by command
`curl -L https://raw.githubusercontent.com/demanuel/NewsUP/master/build_scripts/debian/debian.sh | bash`

**Comment by demanuel** [comment]
I see that you are using perl from perlbrew and not the stock one. The easiest workaround would be to set the environment variable `PERL5LIB` to point to the location of the files.

Can you run the same command, but instead use:
`https://github.com/demanuel/NewsUP/blob/perlbrew/build_scripts/debian/debian.sh`

**Comment by maximuml** [comment]
Still got the same error
`Can't locate NewsUP/Article.pm in @INC`

**Comment by maximuml** [comment]
Just move lib/NewsUP to perl5/perlbrew/perls/perl-5.31.6/lib/5.31.6 and everything is fine

**Comment by demanuel** [comment]
But `perl5/perlbrew/perls/perl-5.31.6/lib/5.31.6` is a local path, not a system one.
I will need to change heavily the script to support perlbrew.

**Comment by demanuel** [comment]
Re-opening as this should be addressed.

For now, install the normal package and then export the library PERL5LIB to the folder where they were installed. (put it in your `.bashrc`)

**Comment by demanuel** [comment]
@maximuml I updated the script, now it can deploy the files to where you want by using the `-l PATH`. This will deploy NewsUP to  `PATH/bin` and `PATH/lib`

With the help of the PERL5LIB environment variable you should be able to deploy to where the perlbrew does the installations

Let me know of any issues

**Comment by demanuel** [comment]
Any progress in this?

**Comment by maximuml** [comment]
All good
