### ISSUE TITLE
Undefined subroutine &NewsUP::Utils::_clear_line

### ISSUE THREAD

**Issue by heigos** [demanuel/NewsUP#86]
https://github.com/demanuel/NewsUP/blob/08aab012e9f4ef8013a6f42e845c92add074f413/lib/NewsUP/Utils.pm#L412

superfluous underscore

**Comment by demanuel** [comment]
That's an embarrassing error 😥. I will fix this as soon as I have time (Sunday)

**Comment by demanuel** [comment]
I had time sooner than expected. Fixed.
