### ISSUE TITLE
Please update your perl version

### ISSUE THREAD

**Issue by uttham29** [demanuel/NewsUP#88]
hey i am having this issue telling me to update my perl version .I compiled & installed from source code from this version perl-5.30.1 .I tried this on both my servers one running on ubuntu 10.04 and another on debian 11 minimal.

**Comment by demanuel** [comment]
>  compiled & installed from source code 

Can you tell what are the steps you did, and their output?

**Comment by uttham29** [comment]
i did this
 wget https://www.cpan.org/src/5.0/perl-5.30.1.tar.gz
tar xvfz perl-5.30.1.tar.gz
cd perl-5.30.1 && ./Configure -Duseithreads -des && make && make test && make install
/usr/local/bin/cpan -u
it finished installing without any warnings and errors

apt install bc git patch wget curl gcc make perl libio-socket-ssl-perl libnet-ssleay-perl libxml-libxml-perl libfile-copy-recursive-perl libconfig-tiny-perl libinline-c-perl

curl -L https://raw.githubusercontent.com/demanuel/NewsUP/master/build_scripts/debian/debian.sh | bash

**Comment by demanuel** [comment]
This is the line where it verifies the perl version: 
https://github.com/demanuel/NewsUP/blob/master/build_scripts/debian/debian.sh#L114

Can you confirm that you have the right perl version on your path? 

Can you run this two commands?
1-

`perl -e 'print join(".", @{$^V->{version}}[0,1])'`

2-

`find . -type f -exec awk '/use 5./{v=(($2+0)%5)*1000; print 5"."v}' {} + | sort -r | head -n 1`

**Comment by uttham29** [comment]
1.  5.28
2.  5.9.005

**Comment by demanuel** [comment]
So the perl you installed isn't on the path. Please fix that.  `perl --version` should show version 5.30

Regarding the second point, are you running the `curl` inside the downloaded perl folder? can you run that command on a folder without perl files. The script executes that `find` pasted above to find the minimum version required for newsup. I believe it's getting confused with the files from the perl installation.

**Comment by demanuel** [comment]
Any progress in this?

**Comment by demanuel** [comment]
Closing as there is no update. Please feel free to re-open it.
