### ISSUE TITLE
Can't locate Inline.pm

### ISSUE THREAD

**Issue by DarkShadowxx** [demanuel/NewsUP#89]
When trying to use newsup, I get the following error:

`Can't locate Inline.pm in @INC (you may need to install the Inline module) (@INC contains: /root/perl5/perlbrew/perls/perl-5.30.2/bin/../lib/5.30.2/x86_64-linux /root/perl5/perlbrew/perls/perl-5.30.2/bin/../lib/5.30.2 /root/perl5/perlbrew/perls/perl-5.30.2/bin/../lib /root/perl5/perlbrew/perls/perl-5.30.2/lib/site_perl/5.30.2/x86_64-linux /root/perl5/perlbrew/perls/perl-5.30.2/lib/site_perl/5.30.2 /root/perl5/perlbrew/perls/perl-5.30.2/lib/5.30.2/x86_64-linux /root/perl5/perlbrew/perls/perl-5.30.2/lib/5.30.2) at /root/perl5/perlbrew/perls/perl-5.30.2/bin/../lib/NewsUP/yEnc.pm line 10.
BEGIN failed--compilation aborted at /root/perl5/perlbrew/perls/perl-5.30.2/bin/../lib/NewsUP/yEnc.pm line 10.
Compilation failed in require at /root/perl5/perlbrew/perls/perl-5.30.2/bin/../lib/NewsUP/Article.pm line 4.
BEGIN failed--compilation aborted at /root/perl5/perlbrew/perls/perl-5.30.2/bin/../lib/NewsUP/Article.pm line 4.
Compilation failed in require at /root/perl5/perlbrew/perls/perl-5.30.2/bin/newsup line 7.
BEGIN failed--compilation aborted at /root/perl5/perlbrew/perls/perl-5.30.2/bin/newsup line 7.`

I installed perl 5.30.2 with Perlbrew and set the environment variables as the script told me when running with -l.

**Comment by demanuel** [comment]
You have to install the Inline module.

If you use perlbrew, do 

> $ perlbrew install-cpanm
> $ cpanm Inline

Let me know if you have any issue

**Comment by DarkShadowxx** [comment]
Thank you. But now I get the following error:

```
root@cloud:~# newsup
Can't locate NewsUP/Article.pm in @INC (you may need to install the NewsUP::Article module) (@INC contains: /usr/local/bin/../lib /usr/local/lib/perl5/site_perl/5.30.1/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.30.1 /usr/local/lib/perl5/5.30.1/x86_64-linux-thread-multi /usr/local/lib/perl5/5.30.1) at /usr/local/bin/newsup line 7.
BEGIN failed--compilation aborted at /usr/local/bin/newsup line 7.
```

**Comment by demanuel** [comment]
on your `~/.bashrc` file add this to the end:

> PERL5LIB=$PERL5LIB:<add here the path to where you put the the lib folder>

**Comment by DarkShadowxx** [comment]
Hm, still getting the same error.

I added `PERL5LIB=$PERL5LIB:/root/perl5/perlbrew/perls/perl-5.30.2/lib/`.

Here is the content of that path:
`root@cloud:~# ls /root/perl5/perlbrew/perls/perl-5.30.2/lib/`
`5.30.2  NewsUP  site_perl
`

**Comment by demanuel** [comment]
I missed a little detail in the previous instruction. Can you export the variable?


> on your `~/.bashrc` file add this to the end:
> 
> `export PERL5LIB=$PERL5LIB:<add here the path to where you put the the lib folder>`
> 
> Then you need to `$ source ~.bashrc`



If it still doesn't work, can you run this and paste the output:  `perl -e "$,=', '; print @INC"`

**Comment by demanuel** [comment]
Closing it as there's no update. Feel free to re-open it.
