### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by peaveyman** [demanuel/NewsUP#9]
I am getting this error.

Failed to connect or ssl handshake: Invalid argument, IO::Socket::IP configuration failed at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 57

**Comment by demanuel** [comment]
Can you provide the parameters you're using?
The error means that there's one parameter wrong... Can you please check if you have the server and the port correct?



Please also provide the perl version you have.

**Comment by peaveyman** [comment]
I got past the ssl problem. I had the server wrong. But now I'm getting this error. I know it's a lot to paste but maybe you can make sense of it. The perl version is 5.22.0 and I'm calling the script with this command: perl /home/gary/NewsUP/newsup.pl -directory

Unknown option: directory
Starting connection 1 for uploading
Starting connection 2 for uploading
Starting connection 3 for uploading
Starting connection 4 for uploading
Starting connection 5 for uploading
Starting connection 6 for uploading
Starting connection 7 for uploading
Starting connection 8 for uploading
Starting connection 9 for uploading
Starting connection 10 for uploading
Starting connection 11 for uploading
Starting connection 12 for uploading
Starting connection 13 for uploading
Starting connection 14 for uploading
Starting connection 15 for uploading
Starting connection 16 for uploading
Starting connection 17 for uploading
Starting connection 18 for uploading
Starting connection 19 for uploading
Starting connection 20 for uploading
Starting connection 21 for uploading
Starting connection 22 for uploading
Starting connection 23 for uploading
Starting connection 24 for uploading
Starting connection 25 for uploading
Starting connection 26 for uploading
Starting connection 27 for uploading
Starting connection 28 for uploading
Starting connection 29 for uploading
Starting connection 30 for uploading
Child 12495 starting header check!
Child 12499 starting header check!
Child 12496 starting header check!
Child 12502 starting header check!
Child 12497 starting header check!
Child 12492 starting header check!
Child 12503 starting header check!
Child 12494 starting header check!
Child 12501 starting header check!
Child 12506 starting header check!
Child 12509 starting header check!
Child 12508 starting header check!
Child 12514 starting header check!
Child 12511 starting header check!
Child 12510 starting header check!
Child 12513 starting header check!
Child 12515 starting header check!
Child 12500 starting header check!
Child 12519 starting header check!
Child 12512 starting header check!
Child 12517 starting header check!
Child 12518 starting header check!
Child 12520 starting header check!
Child 12516 starting header check!
Child 12521 starting header check!
Child 12507 starting header check!
Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Child 12504 starting header check!
Child 12505 starting header check!
Child 12498 starting header check!
Child 12493 starting header check!
Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Parent: Child 12492 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12493 was reaped - Thu Jul  2 09:11:48 2015.
Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Parent: Child 12494 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12495 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12496 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12497 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12498 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12499 was reaped - Thu Jul  2 09:11:48 2015.
Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.
Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.


Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Parent: Child 12500 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12501 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12502 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12503 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12504 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12505 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12506 was reaped - Thu Jul  2 09:11:48 2015.
Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Parent: Child 12507 was reaped - Thu Jul  2 09:11:48 2015.
Parent: Child 12508 was reaped - Thu Jul  2 09:11:48 2015.
Error: Unable to authenticate on the headercheck server! at /home/gary/NewsUP/lib/Net/NNTP/Uploader.pm line 253.

Parent: Child 12509 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12510 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12511 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12512 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12513 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12514 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12515 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12516 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12517 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12518 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12519 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12520 was reaped - Thu Jul  2 09:11:49 2015.
Parent: Child 12521 was reaped - Thu Jul  2 09:11:49 2015.
Transfer speed: [0.00 KBytes/sec]
NZB file 1435846309.nzb created!

**Comment by peaveyman** [comment]
I got past that error about the header check server by letting it using the same server I upload with. But now it's stuck on this: Child 14116 starting header check!

That's just one line but there are a bunch of lines just like that with a different number.

**Comment by demanuel** [comment]
That means you were unable to authenticate on the headercheck server.Probably you ran out of available connections.

 


     On Thursday, July 2, 2015 4:21 PM, peaveyman <notifications@github.com> wrote:
   

 I got past that error about the header check server by letting it using the same server I upload with. But now it's stuck on this: Child 14116 starting header check!That's just one line but there are a bunch of lines just like that with a different number.—

**Comment by peaveyman** [comment]
Even if I leave the header check server blank it still won't upload.

**Comment by demanuel** [comment]
you have a wrong switch:

Unknown option: directory

**Comment by peaveyman** [comment]
Then what should I use to get it to upload the contents of a directory with the name of the directory as the subject?

**Comment by demanuel** [comment]
I'm not getting what you want....

You have a folder with this structure:
*- FOLDER/
   *- file1
   *- file2
   *- file3

You want to upload file1, file2, file3 as "[1/3] folder",  "[2/3] folder", "[3/3] folder"?

You can use -f but it will be "[1/3] file1",  "[2/3] file2", "[3/3] file3"...

**Comment by peaveyman** [comment]
I want the files that are in the folder. But I don't think there is a way for me to get the files that are in the folder to upload with the folder name as the subject.

**Comment by demanuel** [comment]
To get the files in the folder you can use "-f" but they won't be getting the folder name.

**Comment by demanuel** [comment]
Is there any poster that does that?

**Comment by peaveyman** [comment]
Gopoststuff does

**Comment by demanuel** [comment]
Can't you use the -comment ?

**Comment by peaveyman** [comment]
I tried this: perl uploadit.pl -f /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/ -comment Alabama-40_Hour_Week-Flac-1985

But I still get this error: Unknown option: f
Use of uninitialized value $DIRECTORY in string eq at uploadit.pl line 85.
You need to configure the switch -directory

**Comment by demanuel** [comment]
If you're using uploadit.pl you should use the -directory switch.If you're using newsup.pl you need to use the -f

 


     On Friday, July 3, 2015 12:15 PM, peaveyman <notifications@github.com> wrote:
   

 I tried this: perl uploadit.pl -f /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/ -comment Alabama-40_Hour_Week-Flac-1985But I still get this error: Unknown option: f
Use of uninitialized value $DIRECTORY in string eq at uploadit.pl line 85.
You need to configure the switch -directory—

**Comment by peaveyman** [comment]
perl uploadit.pl -directory /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/ -comment Alabama-40_Hour_Week-Flac-1985 gives me this: Can't use an undefined value as a HASH reference at uploadit.pl line 94

**Comment by demanuel** [comment]
Can you please paste your newsup.conf ?
 


     On Friday, July 3, 2015 12:53 PM, peaveyman <notifications@github.com> wrote:
   

 perl uploadit.pl -directory /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/ -comment Alabama-40_Hour_Week-Flac-1985 gives me this: Can't use an undefined value as a HASH reference at uploadit.pl line 94—

**Comment by peaveyman** [comment]
Here it is. I have it placed in ~/.config

[server]
server= 
port= 
connections= 30

[auth]
user= 
password= 

[metadata]
client= NewsUP

[upload]
uploader= 
newsgroup= 

[headerCheck]
enabled= 1
sleep= 300
server=
port=
user=
password=

[generic]
headerCheck= 1
monitoringPort = 8675


[script_vars]
############################
#
# Variables
############################
# Path to newsup script
PATH_TO_UPLOADER=/home/gary/NewsUP/newsup.pl -cfc
# Path to RAR
PATH_TO_RAR=/usr/bin/rar
# RAR volume size in megabytes 
RAR_VOLUME_SIZE=50
# RAR compression level
# If RAR_COMPRESSION is -1 then it will skip it
RAR_COMPRESSION=-1
# RAR Password
RAR_PASSWORD=newsup
# Path to PAR2
PATH_TO_PAR2=/usr/bin/par2
# Folder to where the scripts files should be written
# It's obigatory to terminate on the separator folder char.
TEMP_DIR=/tmp/
# Par recovery %
PAR_REDUNDANCY=20
# Randomize Names
# The names are toggled
RANDOMIZE_NAMES=0

**Comment by demanuel** [comment]
Replace [script_vars] for [other]

**Comment by peaveyman** [comment]
When I did that and ran this: perl uploadit.pl -directory /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/ -comment Alabama-40_Hour_Week-Flac-1985

I got this:

Use of uninitialized value in numeric gt (>) at uploadit.pl line 146.
Use of uninitialized value in concatenation (.) or string at uploadit.pl line 148.

Cannot open /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/.rar

**Comment by demanuel** [comment]
Hello Peavey.

You have an old version of the newsup.conf file. Please update it.

You need to have this options on your newsup.conf:

PATH_TO_UPLOADER
EXTRA_ARGS_TO_UPLOADER
ENABLE_RAR_COMPRESSION
PATH_TO_RAR
EXTRA_ARGS_TO_RAR
ENABLE_SFV_GENERATION
PATH_TO_PAR2
EXTRA_ARGS_TO_PAR2
ENABLE_PAR_CREATION
TEMP_DIR
RANDOMIZE_NAMES

**Comment by demanuel** [comment]
Hello Peavey.
You have an old version of the newsup.conf file. Please update it.






















You need to have this options on your newsup.conf:

PATH_TO_UPLOADER
EXTRA_ARGS_TO_UPLOADER
ENABLE_RAR_COMPRESSION
PATH_TO_RAR
EXTRA_ARGS_TO_RAR
ENABLE_SFV_GENERATION
PATH_TO_PAR2
EXTRA_ARGS_TO_PAR2
ENABLE_PAR_CREATION
TEMP_DIR
RANDOMIZE_NAMES



     On Friday, July 3, 2015 1:48 PM, peaveyman <notifications@github.com> wrote:
   

 When I did that and ran this: perl uploadit.pl -directory /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/ -comment Alabama-40_Hour_Week-Flac-1985I got this:Use of uninitialized value in numeric gt (>) at uploadit.pl line 146.
Use of uninitialized value in concatenation (.) or string at uploadit.pl line 148.Cannot open /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/.rar—

**Comment by peaveyman** [comment]
Ok, I have it uploading but I don't see any pars. Does it place them in the folder with the uploads? Also the naming of the files along with the file count is all wrong. In the discussion we had back in March I used this command to get it named like I needed. 

perl uploadit.pl -f /home/gary/uploads/Allison_Moorer-Crows-Flac-2010/ -name Allison_Moorer-Crows-Flac-2010 -comment Allison_Moorer-Crows-Flac-2010

But now I have to use the -directory switch  when using uploadit.pl. This is fine but the naming scheme is all wrong. I'm getting this: 14/27 "Crows - 01 - Abalone Sky.flac" yEnc (/25)

I need it like this:

Allison_Moorer-Crows-Flac-2010 [14/27] - "Crows - 01 - Abalone Sky.flac" yEnc (/25)

**Comment by peaveyman** [comment]
Also, how do I invoke the newsupseq.sh script?

**Comment by demanuel** [comment]
Please paste your command line.

To run the newsupseq.sh just do "./newsupseq.sh" It will find all the folders inside and upload the files.
Please be aware that i didn't test that script.

I need to figure out a way to have users adding their scripts.

**Comment by peaveyman** [comment]
I used this: perl uploadit.pl -directory /path/to/folder -comment my _ comment 

The -cfc switch is in the newsup.conf file. All I got for the name when it uploaded was the file count at the front and the name of the file after that.

**Comment by demanuel** [comment]
Do you agree with issue #10 ?
Can you give your opinion on it?

**Comment by peaveyman** [comment]
On 07/03/2015 04:36 PM, David Emanuel Santiago wrote:
>
> Do you agree with issue #10 
> <https://github.com/demanuel/NewsUP/issues/10> ?
> Can you give your opinion on it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/demanuel/NewsUP/issues/9#issuecomment-118428674>.
>
I just saw it. Let me look it over and I will reply.

**Comment by demanuel** [comment]
Please update the script from the branch master and use the newsup from branch 10.

Then you can do:

```
perl uploadit.pl -directory YOUR_DIRECTORY -a "-comment \"YOUR_DIRECTORY\""
```

You should get rars and pars (depending on your configuration)

**Comment by peaveyman** [comment]
I need to update the newsup.conf also, correct?

**Comment by demanuel** [comment]
No. I didn't performed any change on it. If you already updated, like you said you did, then it's not required.

**Comment by peaveyman** [comment]
How does this look? Do I need quotes anywhere?

perl uploadit.pl -directory /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/ -a -comment Alabama-40_Hour_Week-Flac-1985

**Comment by demanuel** [comment]
i dropped the -comment on the upload it. 
Now you need to use -a which is extra-args to newsup, like you're doing but you need to escape it like this:

perl uploadit.pl -directory /home/gary/uploads/Alabama-40_Hour_Week-Flac-1985/ -a "-comment Alabama-40_Hour_Week-Flac-1985"

**Comment by peaveyman** [comment]
And if the -cfc switch is not used it can be removed from the newsup.conf

**Comment by demanuel** [comment]
yes :-)

**Comment by peaveyman** [comment]
It's uploading. The subject looks right. Now to see if the pars get uploaded and the header check works right.

**Comment by demanuel** [comment]
The pars and the rars are going to the TEMP_FOLDER

**Comment by peaveyman** [comment]
It looks like it only created 2 par files. That can't be right. One file looks to be incomplete on the server but the header check is still running.

**Comment by demanuel** [comment]
the par is created by invoking the par2 utility with the arguments specified on the configuration file. Probably there's some file that needs to be escaped...

There is a -debug switch for the uploadit.pl script that shows what's doing...  If you can paste the output with -debug switch.

**Comment by peaveyman** [comment]
The upload completed with only 2 pars and one file incomplete. I changed the tmp folder so I know where it's at and am trying another one with the debug switch.

**Comment by peaveyman** [comment]
So far it's not put any par files in the tmp folder and there are 19 files in the folder it's uploading and the file count showing on the server is only 20 so something is off somewhere.

**Comment by peaveyman** [comment]
Ok, it's completed. Doing the header check now but all the files are on the server and it did not create any par files at all this time.

**Comment by peaveyman** [comment]
I found the problem but I'm not sure how to fix it. Here it is:

Invoking: /usr/bin/par2 c -r20 "/home/gary/tmp/American Pride.par2" "/home/gary/uploads/American Pride/Alabama - American Pride.jpg" "/home/gary/uploads/American Pride/American Pride - 02 - Hometown Honeymoon.flac" "/home/gary/uploads/American Pride/cover.jpg" "/home/gary/uploads/American Pride/American Pride - 08 - Between the Two of Them.flac" "/home/gary/uploads/American Pride/American Pride.cue" "/home/gary/uploads/American Pride/American Pride - 11 - Pictures and Memories.flac" "/home/gary/uploads/American Pride/American Pride - 01 - Take a Little Trip.flac" "/home/gary/uploads/American Pride/Alabama - American Pride.m3u" "/home/gary/uploads/American Pride/American Pride - 06 - Richard Petty Fans.flac" "/home/gary/uploads/American Pride/Alabama - American Pride.log" "/home/gary/uploads/American Pride/American Pride - 05 - I'm in a Hurry (And Don't Know Why).flac" "/home/gary/uploads/American Pride/American Pride - 10 - Sometimes out of Touch.flac" "/home/gary/uploads/American Pride/cover (1).jpg" "/home/gary/uploads/American Pride/cover (2).jpg" "/home/gary/uploads/American Pride/American Pride - 07 - Homesick Fever.flac" "/home/gary/uploads/American Pride/Folder.jpg" "/home/gary/uploads/American Pride/American Pride - 04 - You Can't Take the Country out of Me.flac" "/home/gary/uploads/American Pride/American Pride - 03 - Once Upon a Lifetime.flac" "/home/gary/uploads/American Pride/American Pride - 09 - American Pride.flac" "/home/gary/tmpAmerican Pride.sfv"
You must specify a list of files when creating.

**Comment by demanuel** [comment]
The par2 command is correct.
All the file names are under delimited by double quotes....
If you ran that command on your shell, don't you get all the correct pars?

Can you tell me the par2 version you have by running ```par2 -VV``` ? - Capital V

**Comment by peaveyman** [comment]
The par2 version is 0.6.13. It didn't create any pars at all. The last line in my last post says "You must specify a list of files when creating."

**Comment by demanuel** [comment]
I have the same version.

That message isn't from the newsup, but from par2. That's why i asked if you can run that comand in the shell :-)

Does the files that are being par'ed exist?

* "/home/gary/uploads/American Pride/Alabama - American Pride.jpg"
* "/home/gary/uploads/American Pride/American Pride - 02 - Hometown Honeymoon.flac"
* "/home/gary/uploads/American Pride/cover.jpg"
* "/home/gary/uploads/American Pride/American Pride - 08 - Between the Two of Them.flac"
* "/home/gary/uploads/American Pride/American Pride.cue"
* "/home/gary/uploads/American Pride/American Pride - 11 - Pictures and Memories.flac"
* "/home/gary/uploads/American Pride/American Pride - 01 - Take a Little Trip.flac"
* "/home/gary/uploads/American Pride/Alabama - American Pride.m3u"
* "/home/gary/uploads/American Pride/American Pride - 06 - Richard Petty Fans.flac"
* "/home/gary/uploads/American Pride/Alabama - American Pride.log"
* "/home/gary/uploads/American Pride/American Pride - 05 - I'm in a Hurry (And Don't Know Why).flac"
* "/home/gary/uploads/American Pride/American Pride - 10 - Sometimes out of Touch.flac"
* "/home/gary/uploads/American Pride/cover (1).jpg"
* "/home/gary/uploads/American Pride/cover (2).jpg"
* "/home/gary/uploads/American Pride/American Pride - 07 - Homesick Fever.flac"
* "/home/gary/uploads/American Pride/Folder.jpg"
* "/home/gary/uploads/American Pride/American Pride - 04 - You Can't Take the Country out of Me.flac"
* "/home/gary/uploads/American Pride/American Pride - 03 - Once Upon a Lifetime.flac"
* "/home/gary/uploads/American Pride/American Pride - 09 - American Pride.flac"
* "/home/gary/tmpAmerican Pride.sfv"

**Comment by peaveyman** [comment]
Yes, they exist. And yes, the par2 command exists. I have another script I was using that renames the folders to my preferred naming scheme and creates the par files all in one step.

**Comment by demanuel** [comment]
The only thing that i see wrong is the name of the sfv file - which i already fixed.
Other than that i don't have any clue why the par2 isn't creating the par files... :-(

**Comment by peaveyman** [comment]
Okay, thanks for the effort. :)

**Comment by demanuel** [comment]
Sorry i can't be more helpful.

**Comment by shillshocked** [comment]
I have a script that will par groups of subfolders if anyone is interested.

**Comment by demanuel** [comment]
Sure :-)
Can i add it to the scripts folder and distribute it?

**Comment by shillshocked** [comment]
Yeah, do whatever you want with it. It's just a snippet. I haven't figured out how to take a number as input so I can use that instead of the hardcoded value of "-s640000"

par2folders.sh:

#!/bin/bash

for dir in "$PWD"/*; do (cd "$dir" && MYBASENAME=$(basename "$dir") && par2 c -r10 -s640000 -t- "$dir/$MYBASENAME" *); done
