### ISSUE TITLE
The `temp_folder` option isn't defined! at /usr/local/bin/newsup line 45.

### ISSUE THREAD

**Issue by lioilsources** [demanuel/NewsUP#90]
Running NewsUp from docker image under macOS.

Dockerfile
```
FROM ubuntu:20.04
RUN apt-get update

RUN apt-get install --help

ADD configure_timezone.sh /configure_timezone.sh
RUN /configure_timezone.sh

RUN apt-get -y install bc git patch wget curl gcc make perl libio-socket-ssl-perl libnet-ssleay-perl libxml-libxml-perl libfile-copy-recursive-perl libconfig-tiny-perl libinline-c-perl
RUN curl -L https://raw.githubusercontent.com/demanuel/NewsUP/master/build_scripts/debian/debian.sh | bash

ADD config /root/.config

CMD newsup
```

`docker run -v /Users/_/folder:/mnt newsup:latest newsup --file /mnt/file --par2 --splitnpar`

Getting this error:
> The `temp_folder` option isn't defined! at /usr/local/bin/newsup line 45.

**Comment by demanuel** [comment]
If you are using --splitnpar and --par2 you'll need to have a temp_folder defined so it can create the temporary files (the .rar/.7z and the .par2) there.

Do you have a temp_folder defined in the configuration file?

https://github.com/demanuel/NewsUP/blob/master/conf/newsup.conf#L72

Or you can use the command line option --tempFolder=/path/to/temp_folder

**Comment by demanuel** [comment]
Btw, it's been a long time since i played with docker, but 

> ADD config /root/.config

Is this correct? shouldn't be "`ADD conf/newsup.config /root/.config/`"  or something similar ?

**Comment by lioilsources** [comment]
`docker run -t -i -v /Users/_/folder:/mnt newsup:latest bash`

Inside container:
`root@9911fc1bca03:/# cat /root/.config`

```
[server]
server= ***
port= 443
connections= 6
tls = 1
tls_ignore_certificate = 0
# To generate random ids or to use the returned ones from the server. Note: Some servers don't return anything. In that case change this option to 1
generate_ids = 0

[auth]
user= ***
password= ***

[upload]
uploader= NewsUP <NewsUP@somewhere.cbr>
newsgroups= alt.binaries.test
obfuscate = 0
# default value 750KBytes
size = 768000

[headerCheck]
enabled= 1
sleep= 20
retries= 3
connections = 3
server = ***
port = 119
user = ***
password = ***

[metadata]
#You can put here anything you want to appear on the nzb header. It must have the pattern: word= a big one line sentence
client= NewsUP
veryWeirdInfoIWantToPutOnTheNZBMetadata= it's really very weird!

[extraHeaders]
#extra header. It will became X-extra-header
extra-header= value1
#extra header. Non valid because there's already one
X-extra-header= value3
#second extra header
extra-header2= value2
#non valid. Non valid headers are: from, newsgroups, message-id and subject.
from= test


[options]
skip_copy = 0 # If you want to copy the files first to the `temp_folder` option.
splitnpar= 1
# Command that will be used to generate the splitted files
# For rar files use:
# rar a -m0 -v50m -ed -ep1
split_cmd = 7z a -mx0 -v50m -t7z --
# pattern of the files generated with the split_cmd.
# If splitnpar is set to 1, these are the files that
# are going to be uploaded.
# For rar files use:
# *rar
split_pattern = *7z *[0-9][0-9][0-9]
par2 = 1
# full path to par2 executable
par2_path = par2
# this will be used if you use the obfuscation option
par2_rename_settings = c -s768000 -r0
par2_settings = c -s768000 -r15
#temp_folder = /data/tmp # Make sure this folder exists. Even if the skip_copy is set to 1. This folder is still used for the split and par files
temp_folder = /mnt
# if the nzb is also uploaded
upload_nzb = 1
#nzb_save_path = /data/uploads/
nzb_save_path = /mnt/
no_nzb = 1
#before_upload = /script/to/run/before_upload.sh # Make sure the file is executable
```

**Comment by lioilsources** [comment]
This is working!

Dockerfile:
`ADD newsup.config /etc/newsup/`

commandline:
`docker run -v /Users/_/folder:/mnt newsup:latest newsup --file /mnt/file --par2 --splitnpar --configuration /etc/newsup/newsup.config`

> Argument "0 # If you want to copy the files first to the `temp_fol..." isn't numeric in multiplication (*) at /usr/local/bin/newsup line 42.
> sh: 1: 7z: not found                 
> sh: 1: par2: not founds              
> Uploaded 0 MBytes in 0 seconds. Avg. Speed: 0 KBytes/second
> Starting the headercheck
> Sleeping 20 seconds
> Headercheck done in 20.096504 seconds!

**Comment by demanuel** [comment]
> Definitely some trouble with config file naming/storage/container HOME recognition or what ...?

Newsup uses the variable HOME (in case of linux) to find the configuration file:
https://github.com/demanuel/NewsUP/blob/master/lib/NewsUP/Utils.pm#L36

So if you don't want to pass the option "--configuration", then you need to export to the container that environment variable.

Please check, https://docs.docker.com/engine/reference/builder/#env

> Argument "0 # If you want to copy the files first to the `temp_fol..." isn't numeric in multiplication (*) at /usr/local/bin/newsup line 42.
> sh: 1: 7z: not found
> sh: 1: par2: not founds
> Uploaded 0 MBytes in 0 seconds. Avg. Speed: 0 KBytes/second
> Starting the headercheck
> Sleeping 20 seconds
> Headercheck done in 20.096504 seconds!

Does your docker image contains the par2 utility and 7z (or rar) ? If so, then (for some weird reason is not finding them) you have to do one of the following:
1- Put them in the PATH
2- Modify the options "split_cmd", "par2_path" in the config file to include the full path to those utilities.

**Comment by lioilsources** [comment]
Final solution.

Dockerfile
```
FROM ubuntu:20.04

RUN apt-get update

RUN apt-get install -y software-properties-common
RUN add-apt-repository universe
RUN apt-get update

ADD configure_timezone.sh /configure_timezone.sh
RUN /configure_timezone.sh

RUN apt-get -y install bc git patch wget curl gcc make perl libio-socket-ssl-perl libnet-ssleay-perl libxml-libxml-perl libfile-copy-recursive-perl libconfig-tiny-perl libinline-c-perl
RUN apt-get -y install p7zip-full p7zip-rar par2
RUN curl -L https://raw.githubusercontent.com/demanuel/NewsUP/master/build_scripts/debian/debian.sh | bash

ADD newsup.config /etc/newsup/

CMD newsup
```

configure_timezone.sh
```
# set noninteractive installation
export DEBIAN_FRONTEND=noninteractive
apt-get install -y tzdata
ln -fs /usr/share/zoneinfo/Europe/Prague /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
```

newsup.config
```
[server]
server= news.tweaknews.eu
port= 443
...
```

Build command
`docker build . -t newsup:latest`

Upload command:
`mkdir tmp /Users/_/Downloads/folder`
`docker run -v /Users/_/Downloads/folder:/mnt newsup:latest newsup --file /mnt/file --par2 --splitnpar --configuration /etc/newsup/newsup.config`

Output:

> Argument "0 # If you want to copy the files first to the `temp_fol..." isn't numeric in multiplication (*) at /usr/local/bin/newsup line 42.
> Uploaded 395 MBytes in 381 seconds. Avg. Speed: 1060 KBytes/second
> Starting the headercheck
> Sleeping 20 seconds
> Error: Failed to connect or ssl handshake: , SSL connect attempt failed error:1408F10B:SSL routines:ssl3_get_record:wrong version number at /usr/local/bin/newsup line 647.

Next time I will ask for nzb file to test, if upload was successful.

**Comment by lioilsources** [comment]
Multiple 
> The NZB isn't going to be valid. There are unknown articles. Please check output for failures at /usr/share/perl5/NewsUP/Utils.pm line 329.

newsup.config
```
...
nzb_save_path = /mnt/tmp
no_nzb = 0
...
```

**Comment by demanuel** [comment]
Let's go by parts, like jack used to say:

1- 
> Argument "0 # If you want to copy the files first to the `temp_fol..." isn't numeric in multiplication (*) at /usr/local/bin/newsup line 42.

Can you check if in your configuration do you have any non visible character after the zero in the `skip_copy` option? For some reason it's considering all the line (comment included). Or to make it easier, delete the rest of the line after the zero.

It's a warning but you shouldn't be having it.


2-

> Error: Failed to connect or ssl handshake: , SSL connect attempt failed error:1408F10B:SSL routines:ssl3_get_record:wrong version number at /usr/local/bin/newsup line 647.

This is an error. It was not able to connect to the header check server. Please check the headerCheck section in the config file. 


https://github.com/demanuel/NewsUP/blob/master/conf/newsup.conf#L21


3-

> The NZB isn't going to be valid. There are unknown articles. Please check output for failures at /usr/share/perl5/NewsUP/Utils.pm line 329.

You are not generating the IDs. Some servers support it, some don't.

Enable this option:
https://github.com/demanuel/NewsUP/blob/master/conf/newsup.conf#L8

If you already have it enabled, let me know.

> But the NZB exists. I need to check if it is possible to download the file.

It might exist, but it won't be valid. Because of above reason.

**Comment by lioilsources** [comment]
(1) Looks like bug, this works.
```
# If you want to copy the files first to the `temp_folder` option.
skip_copy= 0
```
Sometimes the properties in newsup.config file has format like `property= value` sometimes `property = value` it is confusing, but does not matter.

(2) What does mean `header check server`? I configured it same as upload server but it is not correct (for news.tweaknews.eu). So I disable it.
```
[headerCheck]
enabled= 0
```

(3) Checked last NZB with strange result (NZBGet logs).
> 1 of 1 article downloads failed for "file.avi/.DS_Store"
> Cancelling download and deleting file.avi due to health 84.5% below critical 84.7%

I don't get it. Hidden .DS_Store is inside folder but ...

After correcting configs and save NZB elsewhere than /mnt/tmp (because of cleaning of the content of that folder) it works (even if .DS_Store is present in the uploading folder)!
```
[options]
nzb_save_path = /mnt/uploads/
```

There is no .DS_Store file in downloaded archive.

---

Many thanks, I'm satisfy now.

Hope, dockerized version of your uploader, will help someone else.

**Comment by demanuel** [comment]
> Sometimes the properties in newsup.config file has format like property= value sometimes property = value it is confusing, but does not matter.

There's no difference. `key = value` is the same as `key=value`, `key =value` and `key= value`

You can use any of them.

> What does mean header check server? I configured it same as upload server but it is not correct (for news.tweaknews.eu). So I disable it.

Headerchecking is the process of verifying if all the articles got uploaded. Sometimes (it's getting rarer), you upload an article with success, and for some reason in the server the article disappears. Doing headercheck it will check that the article was successfully uploaded and successfully processed by the server and can be downloaded.

There are also propagation errors, between servers and sometimes the articles are not propagated, so you need to upload that specific article again. That's why you have a possibility of adding another server. If you enable the headercheck and do not define the headercheck servers, it will use the same server that was used for upload.

The option --checkNZB is also related with this. If you pass this option with an NZB it will tell you if the files specified in the NZB are available in the server (it does a headercheck). Usefull to know if your file is in the server or nor, so you can upload it again.


> I don't get it. Hidden .DS_Store is inside folder but ...


The .DS_Store is from the macOS:

https://en.wikipedia.org/wiki/.DS_Store

This is coming from your OS. Are you sure that the folder that you were uploading was empty and it didn't had the .DS_Store file inside?

Unfortunately i cannot help you much more here.
